// French Foundation — sample (~79 cards, ~9% of 863). Register: tu.
// Schema: { en, fr, fr_phon, cat, gender?, note? }
//   gender: "m" | "f" | "mf"  (nouns only — app renders le/la · un/une)
//   fr_phon: respelling for English speakers, stressed syllable in CAPS
const FOUNDATION_FR = [
  // ── greetings (28) ──
  {en:"Hello / Goodbye", fr:"Bonjour / Au revoir", fr_phon:"bohn-ZHOOR / oh ruh-VWAHR", cat:"greetings"},
  {en:"Good night", fr:"Bonne nuit", fr_phon:"bun NWEE", cat:"greetings"},
  {en:"How are you?", fr:"Comment ça va ?", fr_phon:"koh-mahn sa VA", cat:"greetings", note:"tu/familiar; formal: Comment allez-vous ?"},
  {en:"I am fine / well", fr:"Je vais bien", fr_phon:"zhuh vay BYAN", cat:"greetings"},
  {en:"Pleased to meet you", fr:"Enchanté", fr_phon:"ahn-shahn-TAY", cat:"greetings", note:"f: enchantée"},
  {en:"Goodbye / farewell", fr:"Adieu", fr_phon:"a-DYUH", cat:"greetings", note:"final farewell; everyday: au revoir"},
  {en:"Thank you", fr:"Merci", fr_phon:"mair-SEE", cat:"greetings"},
  {en:"Excuse me / Sorry", fr:"Excuse-moi / Pardon", fr_phon:"ek-skuz-MWA / par-DOHN", cat:"greetings", note:"tu form: excuse-moi"},
  {en:"What did you say?", fr:"Qu'est-ce que tu as dit ?", fr_phon:"kes-kuh too a DEE", cat:"greetings"},
  {en:"Never mind / That's alright", fr:"C'est pas grave", fr_phon:"say pa GRAHV", cat:"greetings"},
  {en:"Come quickly!", fr:"Viens vite !", fr_phon:"vyan VEET", cat:"greetings", note:"tu imperative"},
  {en:"Just a moment", fr:"Un moment", fr_phon:"an mo-MAHN", cat:"greetings"},
  {en:"You're welcome", fr:"De rien", fr_phon:"duh RYAN", cat:"greetings"},
  {en:"I have a headache", fr:"J'ai mal à la tête", fr_phon:"zhay mal a la TET", cat:"greetings"},
  {en:"He has a cold", fr:"Il a un rhume", fr_phon:"eel a an ROOM", cat:"greetings"},
  {en:"I am very busy", fr:"Je suis très occupé", fr_phon:"zhuh swee tray zo-koo-PAY", cat:"greetings", note:"f: occupée"},
  {en:"Please come in", fr:"Entre, s'il te plaît", fr_phon:"ahntr seel tuh PLEH", cat:"greetings", note:"tu form"},
  {en:"I've forgotten", fr:"J'ai oublié", fr_phon:"zhay oo-blee-AY", cat:"greetings"},
  {en:"To arrive late", fr:"Arriver en retard", fr_phon:"a-ree-vay ahn ruh-TAR", cat:"greetings"},
  {en:"How much is it?", fr:"C'est combien ?", fr_phon:"say kohn-BYAN", cat:"greetings"},
  {en:"What time is it?", fr:"Quelle heure est-il ?", fr_phon:"kel ur ay-TEEL", cat:"greetings"},
  {en:"What time is it? (alt)", fr:"Il est quelle heure ?", fr_phon:"eel ay kel UR", cat:"greetings", note:"casual word order"},
  {en:"See you again", fr:"À bientôt", fr_phon:"a byan-TOH", cat:"greetings"},
  {en:"See you tomorrow", fr:"À demain", fr_phon:"a duh-MAN", cat:"greetings"},
  {en:"See you later", fr:"À tout à l'heure", fr_phon:"a too ta LUR", cat:"greetings"},
  {en:"No problem", fr:"Pas de problème", fr_phon:"pa duh proh-BLEM", cat:"greetings"},
  {en:"I don't agree", fr:"Je ne suis pas d'accord", fr_phon:"zhuh nuh swee pa da-KOR", cat:"greetings"},
  {en:"I am sorry (regret)", fr:"Je suis désolé", fr_phon:"zhuh swee day-zo-LAY", cat:"greetings", note:"f: désolée"},

  // ── pronouns (9) — French-centric ──
  {en:"I", fr:"je", fr_phon:"zhuh", cat:"pronouns"},
  {en:"you (informal)", fr:"tu", fr_phon:"too", cat:"pronouns", note:"one person you know well"},
  {en:"you (formal / plural)", fr:"vous", fr_phon:"voo", cat:"pronouns", note:"polite, or more than one person"},
  {en:"he", fr:"il", fr_phon:"eel", cat:"pronouns"},
  {en:"she", fr:"elle", fr_phon:"el", cat:"pronouns"},
  {en:"we", fr:"nous", fr_phon:"noo", cat:"pronouns", note:"casual spoken French: on"},
  {en:"they (masculine)", fr:"ils", fr_phon:"eel", cat:"pronouns", note:"all-male or mixed group"},
  {en:"they (feminine)", fr:"elles", fr_phon:"el", cat:"pronouns", note:"all-female group"},
  {en:"one / people (impersonal)", fr:"on", fr_phon:"ohn", cat:"pronouns", note:"very common in everyday speech"},

  // ── family (15) ──
  {en:"father", fr:"le père", fr_phon:"luh PAIR", cat:"family", gender:"m"},
  {en:"mother", fr:"la mère", fr_phon:"la MAIR", cat:"family", gender:"f"},
  {en:"brother", fr:"le frère", fr_phon:"luh FRAIR", cat:"family", gender:"m"},
  {en:"sister", fr:"la sœur", fr_phon:"la SUR", cat:"family", gender:"f"},
  {en:"husband", fr:"le mari", fr_phon:"luh ma-REE", cat:"family", gender:"m"},
  {en:"wife", fr:"la femme", fr_phon:"la FAM", cat:"family", gender:"f", note:"also means 'woman'"},
  {en:"son", fr:"le fils", fr_phon:"luh FEES", cat:"family", gender:"m", note:"the 's' is pronounced"},
  {en:"daughter", fr:"la fille", fr_phon:"la FEEY", cat:"family", gender:"f", note:"also means 'girl'"},
  {en:"grandfather", fr:"le grand-père", fr_phon:"luh grahn-PAIR", cat:"family", gender:"m"},
  {en:"grandmother", fr:"la grand-mère", fr_phon:"la grahn-MAIR", cat:"family", gender:"f"},
  {en:"uncle", fr:"l'oncle", fr_phon:"LOHN-kluh", cat:"family", gender:"m"},
  {en:"aunt", fr:"la tante", fr_phon:"la TAHNT", cat:"family", gender:"f"},
  {en:"friend", fr:"l'ami / l'amie", fr_phon:"la-MEE", cat:"family", gender:"mf", note:"ami (m) / amie (f)"},
  {en:"neighbor", fr:"le voisin / la voisine", fr_phon:"luh vwa-ZAN / la vwa-ZEEN", cat:"family", gender:"mf"},
  {en:"child", fr:"l'enfant", fr_phon:"lahn-FAHN", cat:"family", gender:"mf", note:"un/une enfant"},

  // ── colors (12) — adjectives; note gives feminine agreement ──
  {en:"red", fr:"rouge", fr_phon:"ROOZH", cat:"colors", note:"same m/f"},
  {en:"blue", fr:"bleu", fr_phon:"BLUH", cat:"colors", note:"f: bleue"},
  {en:"green", fr:"vert", fr_phon:"VAIR", cat:"colors", note:"f: verte"},
  {en:"yellow", fr:"jaune", fr_phon:"ZHOHN", cat:"colors", note:"same m/f"},
  {en:"black", fr:"noir", fr_phon:"NWAR", cat:"colors", note:"f: noire"},
  {en:"white", fr:"blanc", fr_phon:"BLAHN", cat:"colors", note:"f: blanche"},
  {en:"pink", fr:"rose", fr_phon:"ROHZ", cat:"colors", note:"same m/f"},
  {en:"orange", fr:"orange", fr_phon:"o-RAHNZH", cat:"colors", note:"invariable"},
  {en:"purple", fr:"violet", fr_phon:"vee-o-LEH", cat:"colors", note:"f: violette"},
  {en:"brown", fr:"marron", fr_phon:"ma-ROHN", cat:"colors", note:"invariable; also brun(e)"},
  {en:"grey", fr:"gris", fr_phon:"GREE", cat:"colors", note:"f: grise"},
  {en:"gold", fr:"doré", fr_phon:"do-RAY", cat:"colors", note:"f: dorée; the metal = l'or"},

  // ── days (7) ──
  {en:"Sunday", fr:"dimanche", fr_phon:"dee-MAHNSH", cat:"days"},
  {en:"Monday", fr:"lundi", fr_phon:"lan-DEE", cat:"days"},
  {en:"Tuesday", fr:"mardi", fr_phon:"mar-DEE", cat:"days"},
  {en:"Wednesday", fr:"mercredi", fr_phon:"mair-kruh-DEE", cat:"days"},
  {en:"Thursday", fr:"jeudi", fr_phon:"zhuh-DEE", cat:"days"},
  {en:"Friday", fr:"vendredi", fr_phon:"vahn-druh-DEE", cat:"days"},
  {en:"Saturday", fr:"samedi", fr_phon:"sam-DEE", cat:"days"},

  // ── weather (10) ──
  {en:"hot (weather)", fr:"il fait chaud", fr_phon:"eel fay SHOH", cat:"weather"},
  {en:"cold (weather)", fr:"il fait froid", fr_phon:"eel fay FRWA", cat:"weather"},
  {en:"cool", fr:"il fait frais", fr_phon:"eel fay FREH", cat:"weather"},
  {en:"it's raining", fr:"il pleut", fr_phon:"eel PLUH", cat:"weather"},
  {en:"sunny", fr:"il fait soleil", fr_phon:"eel fay soh-LAY", cat:"weather", note:"also: ensoleillé"},
  {en:"cloudy", fr:"nuageux", fr_phon:"noo-a-ZHUH", cat:"weather", note:"f: nuageuse"},
  {en:"windy", fr:"il y a du vent", fr_phon:"eel ya doo VAHN", cat:"weather"},
  {en:"humid", fr:"humide", fr_phon:"oo-MEED", cat:"weather", note:"same m/f"},
  {en:"dry season", fr:"la saison sèche", fr_phon:"la say-zohn SESH", cat:"weather", gender:"f"},
  {en:"rainy season", fr:"la saison des pluies", fr_phon:"la say-zohn day PLWEE", cat:"weather", gender:"f"},

  // ── numbers (39) ──
  {en:"0", fr:"zéro", fr_phon:"zay-ROH", cat:"numbers"},
  {en:"1", fr:"un", fr_phon:"UHN", cat:"numbers", note:"f: une"},
  {en:"2", fr:"deux", fr_phon:"DUH", cat:"numbers"},
  {en:"3", fr:"trois", fr_phon:"TRWAH", cat:"numbers"},
  {en:"4", fr:"quatre", fr_phon:"KAT-ruh", cat:"numbers"},
  {en:"5", fr:"cinq", fr_phon:"SANK", cat:"numbers"},
  {en:"6", fr:"six", fr_phon:"SEESS", cat:"numbers"},
  {en:"7", fr:"sept", fr_phon:"SET", cat:"numbers"},
  {en:"8", fr:"huit", fr_phon:"WEET", cat:"numbers"},
  {en:"9", fr:"neuf", fr_phon:"NUHF", cat:"numbers"},
  {en:"10", fr:"dix", fr_phon:"DEESS", cat:"numbers"},
  {en:"11", fr:"onze", fr_phon:"OHNZ", cat:"numbers"},
  {en:"12", fr:"douze", fr_phon:"DOOZ", cat:"numbers"},
  {en:"13", fr:"treize", fr_phon:"TREZ", cat:"numbers"},
  {en:"14", fr:"quatorze", fr_phon:"ka-TORZ", cat:"numbers"},
  {en:"15", fr:"quinze", fr_phon:"KANZ", cat:"numbers"},
  {en:"16", fr:"seize", fr_phon:"SEZ", cat:"numbers"},
  {en:"17", fr:"dix-sept", fr_phon:"dee-SET", cat:"numbers"},
  {en:"18", fr:"dix-huit", fr_phon:"deez-WEET", cat:"numbers"},
  {en:"19", fr:"dix-neuf", fr_phon:"deez-NUHF", cat:"numbers"},
  {en:"20", fr:"vingt", fr_phon:"VAN", cat:"numbers"},
  {en:"21", fr:"vingt-et-un", fr_phon:"van-tay-UHN", cat:"numbers"},
  {en:"30", fr:"trente", fr_phon:"TRAHNT", cat:"numbers"},
  {en:"36", fr:"trente-six", fr_phon:"trahnt-SEESS", cat:"numbers"},
  {en:"40", fr:"quarante", fr_phon:"ka-RAHNT", cat:"numbers"},
  {en:"50", fr:"cinquante", fr_phon:"san-KAHNT", cat:"numbers"},
  {en:"52", fr:"cinquante-deux", fr_phon:"san-kahnt-DUH", cat:"numbers"},
  {en:"60", fr:"soixante", fr_phon:"swa-SAHNT", cat:"numbers"},
  {en:"63", fr:"soixante-trois", fr_phon:"swa-sahnt-TRWAH", cat:"numbers"},
  {en:"70", fr:"soixante-dix", fr_phon:"swa-sahnt-DEESS", cat:"numbers", note:"literally 'sixty-ten'"},
  {en:"75", fr:"soixante-quinze", fr_phon:"swa-sahnt-KANZ", cat:"numbers"},
  {en:"80", fr:"quatre-vingts", fr_phon:"kat-ruh-VAN", cat:"numbers", note:"literally 'four-twenties'"},
  {en:"88", fr:"quatre-vingt-huit", fr_phon:"kat-ruh-van-WEET", cat:"numbers"},
  {en:"90", fr:"quatre-vingt-dix", fr_phon:"kat-ruh-van-DEESS", cat:"numbers", note:"literally 'four-twenty-ten'"},
  {en:"100", fr:"cent", fr_phon:"SAHN", cat:"numbers"},
  {en:"1000", fr:"mille", fr_phon:"MEEL", cat:"numbers"},
  {en:"10000", fr:"dix mille", fr_phon:"dee MEEL", cat:"numbers"},
  {en:"100000", fr:"cent mille", fr_phon:"sahn MEEL", cat:"numbers"},
  {en:"1000000", fr:"un million", fr_phon:"uhn meel-YOHN", cat:"numbers"},

  // ── time (39) ──
  {en:"now", fr:"maintenant", fr_phon:"man-tuh-NAHN", cat:"time"},
  {en:"today", fr:"aujourd'hui", fr_phon:"oh-zhoor-DWEE", cat:"time"},
  {en:"tomorrow", fr:"demain", fr_phon:"duh-MAN", cat:"time"},
  {en:"yesterday", fr:"hier", fr_phon:"ee-YAIR", cat:"time"},
  {en:"the day before yesterday", fr:"avant-hier", fr_phon:"a-vahn-tee-YAIR", cat:"time"},
  {en:"the day after tomorrow", fr:"après-demain", fr_phon:"a-preh-duh-MAN", cat:"time"},
  {en:"this week", fr:"cette semaine", fr_phon:"set suh-MEN", cat:"time"},
  {en:"next week", fr:"la semaine prochaine", fr_phon:"la suh-men pro-SHEN", cat:"time"},
  {en:"last week", fr:"la semaine dernière", fr_phon:"la suh-men dair-NYAIR", cat:"time"},
  {en:"this month", fr:"ce mois-ci", fr_phon:"suh mwa-SEE", cat:"time"},
  {en:"next month", fr:"le mois prochain", fr_phon:"luh mwa pro-SHAN", cat:"time"},
  {en:"last month", fr:"le mois dernier", fr_phon:"luh mwa dair-NYAY", cat:"time"},
  {en:"this year", fr:"cette année", fr_phon:"set a-NAY", cat:"time"},
  {en:"next year", fr:"l'année prochaine", fr_phon:"la-nay pro-SHEN", cat:"time"},
  {en:"last year", fr:"l'année dernière", fr_phon:"la-nay dair-NYAIR", cat:"time"},
  {en:"day", fr:"le jour", fr_phon:"luh ZHOOR", cat:"time", gender:"m"},
  {en:"week", fr:"la semaine", fr_phon:"la suh-MEN", cat:"time", gender:"f"},
  {en:"month", fr:"le mois", fr_phon:"luh MWAH", cat:"time", gender:"m"},
  {en:"year", fr:"l'année", fr_phon:"la-NAY", cat:"time", gender:"f", note:"also l'an (m)"},
  {en:"next (modifier)", fr:"prochain", fr_phon:"pro-SHAN", cat:"time", note:"f: prochaine; follows the noun"},
  {en:"last/ago/previous (modifier)", fr:"dernier", fr_phon:"dair-NYAY", cat:"time", note:"f: dernière"},
  {en:"within", fr:"dans", fr_phon:"DAHN", cat:"time", note:"e.g. dans deux jours = in two days"},
  {en:"more", fr:"encore", fr_phon:"ahn-KOR", cat:"time"},
  {en:"within (phǎai-nai)", fr:"d'ici", fr_phon:"dee-SEE", cat:"time", note:"d'ici demain = by tomorrow"},
  {en:"morning", fr:"le matin", fr_phon:"luh ma-TAN", cat:"time", gender:"m"},
  {en:"midday", fr:"midi", fr_phon:"mee-DEE", cat:"time"},
  {en:"afternoon (1pm-5pm)", fr:"l'après-midi", fr_phon:"la-preh-mee-DEE", cat:"time", gender:"m"},
  {en:"afternoon (5pm-9pm)", fr:"le début de soirée", fr_phon:"luh day-bew duh swa-RAY", cat:"time", gender:"m"},
  {en:"evening", fr:"le soir", fr_phon:"luh SWAR", cat:"time", gender:"m"},
  {en:"night", fr:"la nuit", fr_phon:"la NWEE", cat:"time", gender:"f"},
  {en:"this morning", fr:"ce matin", fr_phon:"suh ma-TAN", cat:"time"},
  {en:"this evening", fr:"ce soir", fr_phon:"suh SWAR", cat:"time"},
  {en:"this afternoon", fr:"cet après-midi", fr_phon:"set a-preh-mee-DEE", cat:"time"},
  {en:"tonight", fr:"ce soir", fr_phon:"suh SWAR", cat:"time", note:"cette nuit = later in the night"},
  {en:"breakfast", fr:"le petit-déjeuner", fr_phon:"luh puh-tee-day-zhuh-NAY", cat:"time", gender:"m"},
  {en:"lunch", fr:"le déjeuner", fr_phon:"luh day-zhuh-NAY", cat:"time", gender:"m"},
  {en:"dinner", fr:"le dîner", fr_phon:"luh dee-NAY", cat:"time", gender:"m"},
  {en:"snack", fr:"le goûter", fr_phon:"luh goo-TAY", cat:"time", gender:"m", note:"also un en-cas"},
  {en:"to eat, to dine", fr:"manger", fr_phon:"mahn-ZHAY", cat:"time"},

  // ── months (12) — French months are lowercase, all masculine ──
  {en:"January", fr:"janvier", fr_phon:"zhahn-vee-AY", cat:"months"},
  {en:"February", fr:"février", fr_phon:"fay-vree-AY", cat:"months"},
  {en:"March", fr:"mars", fr_phon:"MARSS", cat:"months"},
  {en:"April", fr:"avril", fr_phon:"a-VREEL", cat:"months"},
  {en:"May", fr:"mai", fr_phon:"MEH", cat:"months"},
  {en:"June", fr:"juin", fr_phon:"ZHWAN", cat:"months"},
  {en:"July", fr:"juillet", fr_phon:"zhwee-YEH", cat:"months"},
  {en:"August", fr:"août", fr_phon:"OOT", cat:"months"},
  {en:"September", fr:"septembre", fr_phon:"sep-TAHM-bruh", cat:"months"},
  {en:"October", fr:"octobre", fr_phon:"ok-TOH-bruh", cat:"months"},
  {en:"November", fr:"novembre", fr_phon:"no-VAHM-bruh", cat:"months"},
  {en:"December", fr:"décembre", fr_phon:"day-SAHM-bruh", cat:"months"},

  // ── questions (18) — tu register ──
  {en:"when?", fr:"quand ?", fr_phon:"KAHN", cat:"questions"},
  {en:"what?", fr:"quoi ?", fr_phon:"KWAH", cat:"questions", note:"qu'est-ce que… at the start of a sentence"},
  {en:"why?", fr:"pourquoi ?", fr_phon:"poor-KWAH", cat:"questions"},
  {en:"how?", fr:"comment ?", fr_phon:"koh-MAHN", cat:"questions"},
  {en:"who?", fr:"qui ?", fr_phon:"KEE", cat:"questions"},
  {en:"where?", fr:"où ?", fr_phon:"OO", cat:"questions"},
  {en:"how many?", fr:"combien ?", fr_phon:"kohn-BYAN", cat:"questions", note:"combien de + noun"},
  {en:"how much?", fr:"combien ?", fr_phon:"kohn-BYAN", cat:"questions"},
  {en:"When will you go to Bangkok?", fr:"Quand vas-tu à Bangkok ?", fr_phon:"kahn va-too a bahng-KOK", cat:"questions"},
  {en:"When did she come (arrive)?", fr:"Quand est-elle arrivée ?", fr_phon:"kahn ay-tel a-ree-VAY", cat:"questions"},
  {en:"What are you doing?", fr:"Qu'est-ce que tu fais ?", fr_phon:"kes-kuh too FEH", cat:"questions"},
  {en:"What is she doing here?", fr:"Qu'est-ce qu'elle fait ici ?", fr_phon:"kes-kel feh ee-SEE", cat:"questions"},
  {en:"What did you say?", fr:"Qu'est-ce que tu as dit ?", fr_phon:"kes-kuh too a DEE", cat:"questions"},
  {en:"Why are you sitting here?", fr:"Pourquoi es-tu assis ici ?", fr_phon:"poor-kwa ay-too a-see ee-SEE", cat:"questions", note:"f: assise"},
  {en:"Why did she come yesterday?", fr:"Pourquoi est-elle venue hier ?", fr_phon:"poor-kwa ay-tel vuh-noo ee-YAIR", cat:"questions"},
  {en:"How will you go to Bangkok?", fr:"Comment vas-tu à Bangkok ?", fr_phon:"koh-mahn va-too a bahng-KOK", cat:"questions"},
  {en:"How can you eat that?", fr:"Comment peux-tu manger ça ?", fr_phon:"koh-mahn puh-too mahn-zhay SA", cat:"questions"},
  {en:"How can you remember?", fr:"Comment fais-tu pour t'en souvenir ?", fr_phon:"koh-mahn feh-too poor tahn soov-NEER", cat:"questions"},

  // ── quantifiers (20) ──
  {en:"many / a lot", fr:"beaucoup", fr_phon:"boh-KOO", cat:"quantifiers", note:"beaucoup de + noun"},
  {en:"many people", fr:"beaucoup de gens", fr_phon:"boh-koo duh ZHAHN", cat:"quantifiers"},
  {en:"many books", fr:"beaucoup de livres", fr_phon:"boh-koo duh LEEV-ruh", cat:"quantifiers"},
  {en:"many cars", fr:"beaucoup de voitures", fr_phon:"boh-koo duh vwa-TEWR", cat:"quantifiers"},
  {en:"many houses", fr:"beaucoup de maisons", fr_phon:"boh-koo duh meh-ZOHN", cat:"quantifiers"},
  {en:"many rooms", fr:"beaucoup de pièces", fr_phon:"boh-koo duh PYESS", cat:"quantifiers"},
  {en:"many newspapers", fr:"beaucoup de journaux", fr_phon:"boh-koo duh zhoor-NOH", cat:"quantifiers"},
  {en:"not many / a few", fr:"peu de", fr_phon:"puh DUH", cat:"quantifiers", note:"peu de + noun"},
  {en:"not many people", fr:"peu de gens", fr_phon:"puh duh ZHAHN", cat:"quantifiers"},
  {en:"not many books", fr:"peu de livres", fr_phon:"puh duh LEEV-ruh", cat:"quantifiers"},
  {en:"not many rooms", fr:"peu de pièces", fr_phon:"puh duh PYESS", cat:"quantifiers"},
  {en:"not many houses", fr:"peu de maisons", fr_phon:"puh duh meh-ZOHN", cat:"quantifiers"},
  {en:"only one / alone / just one", fr:"un seul", fr_phon:"uhn SUHL", cat:"quantifiers", note:"f: une seule"},
  {en:"just one person", fr:"une seule personne", fr_phon:"ewn suhl pair-SUN", cat:"quantifiers"},
  {en:"just one room", fr:"une seule pièce", fr_phon:"ewn suhl PYESS", cat:"quantifiers"},
  {en:"just one dog", fr:"un seul chien", fr_phon:"uhn suhl SHYAN", cat:"quantifiers"},
  {en:"only one book", fr:"un seul livre", fr_phon:"uhn suhl LEEV-ruh", cat:"quantifiers"},
  {en:"only one TV", fr:"une seule télé", fr_phon:"ewn suhl tay-LAY", cat:"quantifiers"},
  {en:"just once (one time)", fr:"une seule fois", fr_phon:"ewn suhl FWAH", cat:"quantifiers"},
  {en:"just one (alone)", fr:"tout seul", fr_phon:"too SUHL", cat:"quantifiers", note:"f: toute seule"},

  // ── verbs (110) — infinitives ──
  {en:"come", fr:"venir", fr_phon:"vuh-NEER", cat:"verbs"},
  {en:"go", fr:"aller", fr_phon:"a-LAY", cat:"verbs"},
  {en:"eat", fr:"manger", fr_phon:"mahn-ZHAY", cat:"verbs"},
  {en:"drink", fr:"boire", fr_phon:"BWAR", cat:"verbs"},
  {en:"work", fr:"travailler", fr_phon:"tra-va-YAY", cat:"verbs"},
  {en:"do / make", fr:"faire", fr_phon:"FAIR", cat:"verbs"},
  {en:"sit", fr:"s'asseoir", fr_phon:"sa-SWAR", cat:"verbs"},
  {en:"sleep", fr:"dormir", fr_phon:"dor-MEER", cat:"verbs"},
  {en:"look / watch", fr:"regarder", fr_phon:"ruh-gar-DAY", cat:"verbs"},
  {en:"listen / hear", fr:"écouter", fr_phon:"ay-koo-TAY", cat:"verbs"},
  {en:"speak", fr:"parler", fr_phon:"par-LAY", cat:"verbs"},
  {en:"write", fr:"écrire", fr_phon:"ay-KREER", cat:"verbs"},
  {en:"read", fr:"lire", fr_phon:"LEER", cat:"verbs"},
  {en:"think", fr:"penser", fr_phon:"pahn-SAY", cat:"verbs"},
  {en:"know (a person/place)", fr:"connaître", fr_phon:"koh-NET-ruh", cat:"verbs", note:"connaître = be familiar with"},
  {en:"know (fact/info)", fr:"savoir", fr_phon:"sa-VWAR", cat:"verbs", note:"savoir = know a fact"},
  {en:"understand", fr:"comprendre", fr_phon:"kohn-PRAHN-druh", cat:"verbs"},
  {en:"like", fr:"aimer bien", fr_phon:"eh-may BYAN", cat:"verbs"},
  {en:"love", fr:"aimer", fr_phon:"eh-MAY", cat:"verbs"},
  {en:"remember", fr:"se souvenir", fr_phon:"suh soov-NEER", cat:"verbs"},
  {en:"see", fr:"voir", fr_phon:"VWAR", cat:"verbs"},
  {en:"hear", fr:"entendre", fr_phon:"ahn-TAHN-druh", cat:"verbs"},
  {en:"call (phone)", fr:"appeler", fr_phon:"ap-LAY", cat:"verbs"},
  {en:"wait", fr:"attendre", fr_phon:"a-TAHN-druh", cat:"verbs"},
  {en:"swim", fr:"nager", fr_phon:"na-ZHAY", cat:"verbs"},
  {en:"run", fr:"courir", fr_phon:"koo-REER", cat:"verbs"},
  {en:"fly", fr:"voler", fr_phon:"vo-LAY", cat:"verbs"},
  {en:"walk", fr:"marcher", fr_phon:"mar-SHAY", cat:"verbs"},
  {en:"drive (car)", fr:"conduire", fr_phon:"kohn-DWEER", cat:"verbs"},
  {en:"ride (motorcycle)", fr:"faire de la moto", fr_phon:"fair duh la mo-TOH", cat:"verbs"},
  {en:"ride (a vehicle)", fr:"prendre", fr_phon:"PRAHN-druh", cat:"verbs", note:"prendre le bus/train"},
  {en:"take a train", fr:"prendre le train", fr_phon:"prahn-druh luh TRAN", cat:"verbs"},
  {en:"want to", fr:"vouloir", fr_phon:"voo-LWAR", cat:"verbs", note:"je veux + infinitif"},
  {en:"would like to / just want", fr:"aimerais", fr_phon:"em-RAY", cat:"verbs", note:"j'aimerais = I would like (polite)"},
  {en:"eat ", fr:"manger", fr_phon:"mahn-ZHAY", cat:"verbs"},
  {en:"drink ", fr:"boire", fr_phon:"BWAR", cat:"verbs"},
  {en:"sleep ", fr:"dormir", fr_phon:"dor-MEER", cat:"verbs"},
  {en:"wake up", fr:"se réveiller", fr_phon:"suh ray-vay-YAY", cat:"verbs"},
  {en:"go ", fr:"aller", fr_phon:"a-LAY", cat:"verbs"},
  {en:"come ", fr:"venir", fr_phon:"vuh-NEER", cat:"verbs"},
  {en:"want", fr:"vouloir", fr_phon:"voo-LWAR", cat:"verbs"},
  {en:"don't want", fr:"ne pas vouloir", fr_phon:"nuh pa voo-LWAR", cat:"verbs", note:"je ne veux pas"},
  {en:"like ", fr:"aimer bien", fr_phon:"eh-may BYAN", cat:"verbs"},
  {en:"love ", fr:"aimer", fr_phon:"eh-MAY", cat:"verbs"},
  {en:"hate", fr:"détester", fr_phon:"day-tes-TAY", cat:"verbs"},
  {en:"see ", fr:"voir", fr_phon:"VWAR", cat:"verbs"},
  {en:"look / watch ", fr:"regarder", fr_phon:"ruh-gar-DAY", cat:"verbs"},
  {en:"listen", fr:"écouter", fr_phon:"ay-koo-TAY", cat:"verbs"},
  {en:"speak / talk", fr:"parler", fr_phon:"par-LAY", cat:"verbs"},
  {en:"read ", fr:"lire", fr_phon:"LEER", cat:"verbs"},
  {en:"write ", fr:"écrire", fr_phon:"ay-KREER", cat:"verbs"},
  {en:"understand ", fr:"comprendre", fr_phon:"kohn-PRAHN-druh", cat:"verbs"},
  {en:"know", fr:"savoir", fr_phon:"sa-VWAR", cat:"verbs"},
  {en:"think ", fr:"penser", fr_phon:"pahn-SAY", cat:"verbs"},
  {en:"forget", fr:"oublier", fr_phon:"oo-blee-AY", cat:"verbs"},
  {en:"help", fr:"aider", fr_phon:"eh-DAY", cat:"verbs"},
  {en:"buy", fr:"acheter", fr_phon:"ash-TAY", cat:"verbs"},
  {en:"sell", fr:"vendre", fr_phon:"VAHN-druh", cat:"verbs"},
  {en:"pay", fr:"payer", fr_phon:"peh-YAY", cat:"verbs"},
  {en:"don't have", fr:"ne pas avoir", fr_phon:"nuh pa a-VWAR", cat:"verbs", note:"je n'ai pas"},
  {en:"can", fr:"pouvoir", fr_phon:"poo-VWAR", cat:"verbs", note:"je peux + infinitif"},
  {en:"cannot", fr:"ne pas pouvoir", fr_phon:"nuh pa poo-VWAR", cat:"verbs", note:"je ne peux pas"},
  {en:"stay / live", fr:"rester", fr_phon:"res-TAY", cat:"verbs", note:"habiter = to reside"},
  {en:"sit ", fr:"s'asseoir", fr_phon:"sa-SWAR", cat:"verbs"},
  {en:"stand", fr:"se lever", fr_phon:"suh luh-VAY", cat:"verbs", note:"être debout = to be standing"},
  {en:"walk ", fr:"marcher", fr_phon:"mar-SHAY", cat:"verbs"},
  {en:"run ", fr:"courir", fr_phon:"koo-REER", cat:"verbs"},
  {en:"drive", fr:"conduire", fr_phon:"kohn-DWEER", cat:"verbs"},
  {en:"ride (motorbike)", fr:"faire de la moto", fr_phon:"fair duh la mo-TOH", cat:"verbs"},
  {en:"swim ", fr:"nager", fr_phon:"na-ZHAY", cat:"verbs"},
  {en:"cook", fr:"cuisiner", fr_phon:"kwee-zee-NAY", cat:"verbs"},
  {en:"clean", fr:"nettoyer", fr_phon:"net-twa-YAY", cat:"verbs"},
  {en:"wash", fr:"laver", fr_phon:"la-VAY", cat:"verbs"},
  {en:"open", fr:"ouvrir", fr_phon:"oo-VREER", cat:"verbs"},
  {en:"close", fr:"fermer", fr_phon:"fair-MAY", cat:"verbs"},
  {en:"call (phone) ", fr:"appeler", fr_phon:"ap-LAY", cat:"verbs"},
  {en:"send", fr:"envoyer", fr_phon:"ahn-vwa-YAY", cat:"verbs"},
  {en:"receive", fr:"recevoir", fr_phon:"ruh-suh-VWAR", cat:"verbs"},
  {en:"find", fr:"trouver", fr_phon:"troo-VAY", cat:"verbs"},
  {en:"give", fr:"donner", fr_phon:"doh-NAY", cat:"verbs"},
  {en:"take", fr:"prendre", fr_phon:"PRAHN-druh", cat:"verbs"},
  {en:"leave / go out", fr:"sortir", fr_phon:"sor-TEER", cat:"verbs", note:"partir = to leave/depart"},
  {en:"arrive", fr:"arriver", fr_phon:"a-ree-VAY", cat:"verbs"},
  {en:"wait ", fr:"attendre", fr_phon:"a-TAHN-druh", cat:"verbs"},
  {en:"meet", fr:"rencontrer", fr_phon:"rahn-kohn-TRAY", cat:"verbs"},
  {en:"ask", fr:"demander", fr_phon:"duh-mahn-DAY", cat:"verbs"},
  {en:"answer", fr:"répondre", fr_phon:"ray-POHN-druh", cat:"verbs"},
  {en:"study", fr:"étudier", fr_phon:"ay-tew-dee-AY", cat:"verbs"},
  {en:"work ", fr:"travailler", fr_phon:"tra-va-YAY", cat:"verbs"},
  {en:"play", fr:"jouer", fr_phon:"zhoo-AY", cat:"verbs"},
  {en:"sing", fr:"chanter", fr_phon:"shahn-TAY", cat:"verbs"},
  {en:"dance", fr:"danser", fr_phon:"dahn-SAY", cat:"verbs"},
  {en:"laugh", fr:"rire", fr_phon:"REER", cat:"verbs"},
  {en:"cry", fr:"pleurer", fr_phon:"pluh-RAY", cat:"verbs"},
  {en:"smile", fr:"sourire", fr_phon:"soo-REER", cat:"verbs"},
  {en:"worry", fr:"s'inquiéter", fr_phon:"san-kyay-TAY", cat:"verbs"},
  {en:"hurry", fr:"se dépêcher", fr_phon:"suh day-peh-SHAY", cat:"verbs"},
  {en:"rest", fr:"se reposer", fr_phon:"suh ruh-poh-ZAY", cat:"verbs"},
  {en:"exercise", fr:"faire du sport", fr_phon:"fair dew SPOR", cat:"verbs"},
  {en:"shower", fr:"se doucher", fr_phon:"suh doo-SHAY", cat:"verbs"},
  {en:"return", fr:"retourner", fr_phon:"ruh-toor-NAY", cat:"verbs", note:"revenir = to come back"},
  {en:"borrow", fr:"emprunter", fr_phon:"ahn-pruhn-TAY", cat:"verbs"},
  {en:"try", fr:"essayer", fr_phon:"eh-seh-YAY", cat:"verbs"},
  {en:"check", fr:"vérifier", fr_phon:"vay-ree-fee-AY", cat:"verbs"},
  {en:"change", fr:"changer", fr_phon:"shahn-ZHAY", cat:"verbs"},
  {en:"choose", fr:"choisir", fr_phon:"shwa-ZEER", cat:"verbs"},
  {en:"use", fr:"utiliser", fr_phon:"ew-tee-lee-ZAY", cat:"verbs"},
  {en:"start", fr:"commencer", fr_phon:"koh-mahn-SAY", cat:"verbs"},
  {en:"finish", fr:"finir", fr_phon:"fee-NEER", cat:"verbs"},
  {en:"lose", fr:"perdre", fr_phon:"PAIR-druh", cat:"verbs"},

  // ── nouns (34) ──
  {en:"chair", fr:"la chaise", fr_phon:"la SHEZ", cat:"nouns", gender:"f"},
  {en:"table", fr:"la table", fr_phon:"la TAB-luh", cat:"nouns", gender:"f"},
  {en:"sofa", fr:"le canapé", fr_phon:"luh ka-na-PAY", cat:"nouns", gender:"m"},
  {en:"fridge", fr:"le frigo", fr_phon:"luh free-GOH", cat:"nouns", gender:"m", note:"le réfrigérateur (formal)"},
  {en:"wardrobe / closet", fr:"l'armoire", fr_phon:"lar-MWAR", cat:"nouns", gender:"f"},
  {en:"plate", fr:"l'assiette", fr_phon:"la-SYET", cat:"nouns", gender:"f"},
  {en:"glass", fr:"le verre", fr_phon:"luh VAIR", cat:"nouns", gender:"m"},
  {en:"spoon", fr:"la cuillère", fr_phon:"la kwee-YAIR", cat:"nouns", gender:"f"},
  {en:"fork", fr:"la fourchette", fr_phon:"la foor-SHET", cat:"nouns", gender:"f"},
  {en:"knife", fr:"le couteau", fr_phon:"luh koo-TOH", cat:"nouns", gender:"m"},
  {en:"kettle", fr:"la bouilloire", fr_phon:"la boo-YWAR", cat:"nouns", gender:"f"},
  {en:"cup", fr:"la tasse", fr_phon:"la TASS", cat:"nouns", gender:"f"},
  {en:"food", fr:"la nourriture", fr_phon:"la noo-ree-TEWR", cat:"nouns", gender:"f"},
  {en:"microwave", fr:"le micro-ondes", fr_phon:"luh mee-kroh-OHND", cat:"nouns", gender:"m"},
  {en:"water", fr:"l'eau", fr_phon:"LOH", cat:"nouns", gender:"f"},
  {en:"swim", fr:"nager", fr_phon:"na-ZHAY", cat:"nouns", note:"source mislabels this — it's the verb 'to swim'"},
  {en:"shirt / blouse", fr:"la chemise", fr_phon:"la shuh-MEEZ", cat:"nouns", gender:"f"},
  {en:"T-shirt", fr:"le tee-shirt", fr_phon:"luh tee-SHURT", cat:"nouns", gender:"m"},
  {en:"handbag", fr:"le sac à main", fr_phon:"luh sak a MAN", cat:"nouns", gender:"m"},
  {en:"skirt", fr:"la jupe", fr_phon:"la ZHEWP", cat:"nouns", gender:"f"},
  {en:"shorts", fr:"le short", fr_phon:"luh SHORT", cat:"nouns", gender:"m"},
  {en:"denim jeans", fr:"le jean", fr_phon:"luh DJEEN", cat:"nouns", gender:"m"},
  {en:"hat", fr:"le chapeau", fr_phon:"luh sha-POH", cat:"nouns", gender:"m"},
  {en:"umbrella", fr:"le parapluie", fr_phon:"luh pa-ra-PLWEE", cat:"nouns", gender:"m"},
  {en:"smartphone", fr:"le smartphone", fr_phon:"luh smart-FON", cat:"nouns", gender:"m"},
  {en:"notebook", fr:"le carnet", fr_phon:"luh kar-NEH", cat:"nouns", gender:"m"},
  {en:"fan", fr:"le ventilateur", fr_phon:"luh vahn-tee-la-TUR", cat:"nouns", gender:"m"},
  {en:"TV", fr:"la télé", fr_phon:"la tay-LAY", cat:"nouns", gender:"f"},
  {en:"computer", fr:"l'ordinateur", fr_phon:"lor-dee-na-TUR", cat:"nouns", gender:"m"},
  {en:"remote control", fr:"la télécommande", fr_phon:"la tay-lay-koh-MAHND", cat:"nouns", gender:"f"},
  {en:"tablet", fr:"la tablette", fr_phon:"la ta-BLET", cat:"nouns", gender:"f"},
  {en:"air-con", fr:"la clim", fr_phon:"la KLEEM", cat:"nouns", gender:"f", note:"la climatisation"},
  {en:"door", fr:"la porte", fr_phon:"la PORT", cat:"nouns", gender:"f"},
  {en:"window", fr:"la fenêtre", fr_phon:"la fuh-NET-ruh", cat:"nouns", gender:"f"},

  // ── adjectives (87) — masculine form; feminine in note ──
  {en:"big / large", fr:"grand", fr_phon:"GRAHN", cat:"adjectives", note:"f: grande"},
  {en:"small", fr:"petit", fr_phon:"puh-TEE", cat:"adjectives", note:"f: petite"},
  {en:"open / on", fr:"ouvert", fr_phon:"oo-VAIR", cat:"adjectives", note:"f: ouverte"},
  {en:"shut / closed / off", fr:"fermé", fr_phon:"fair-MAY", cat:"adjectives", note:"f: fermée"},
  {en:"clean", fr:"propre", fr_phon:"PROP-ruh", cat:"adjectives", note:"same m/f"},
  {en:"dirty", fr:"sale", fr_phon:"SAL", cat:"adjectives", note:"same m/f"},
  {en:"wide", fr:"large", fr_phon:"LARZH", cat:"adjectives", note:"same m/f"},
  {en:"narrow", fr:"étroit", fr_phon:"ay-TRWA", cat:"adjectives", note:"f: étroite"},
  {en:"long", fr:"long", fr_phon:"LOHN", cat:"adjectives", note:"f: longue"},
  {en:"short (height)", fr:"petit", fr_phon:"puh-TEE", cat:"adjectives", note:"f: petite"},
  {en:"high / tall", fr:"haut", fr_phon:"OH", cat:"adjectives", note:"f: haute"},
  {en:"light weight", fr:"léger", fr_phon:"lay-ZHAY", cat:"adjectives", note:"f: légère"},
  {en:"heavy weight", fr:"lourd", fr_phon:"LOOR", cat:"adjectives", note:"f: lourde"},
  {en:"full", fr:"plein", fr_phon:"PLAN", cat:"adjectives", note:"f: pleine"},
  {en:"empty", fr:"vide", fr_phon:"VEED", cat:"adjectives", note:"same m/f"},
  {en:"sharp (pointed)", fr:"pointu", fr_phon:"pwan-TEW", cat:"adjectives", note:"f: pointue"},
  {en:"sharp (blade)", fr:"tranchant", fr_phon:"trahn-SHAHN", cat:"adjectives", note:"f: tranchante"},
  {en:"new", fr:"nouveau", fr_phon:"noo-VOH", cat:"adjectives", note:"f: nouvelle; neuf = brand-new"},
  {en:"old (object)", fr:"vieux", fr_phon:"VYUH", cat:"adjectives", note:"f: vieille"},
  {en:"old (person/animal)", fr:"âgé", fr_phon:"a-ZHAY", cat:"adjectives", note:"f: âgée"},
  {en:"hot", fr:"chaud", fr_phon:"SHOH", cat:"adjectives", note:"f: chaude"},
  {en:"cold (objects)", fr:"froid", fr_phon:"FRWA", cat:"adjectives", note:"f: froide"},
  {en:"warm / to warm", fr:"tiède", fr_phon:"TYED", cat:"adjectives", note:"réchauffer = to warm up"},
  {en:"low (height)", fr:"bas", fr_phon:"BAH", cat:"adjectives", note:"f: basse"},
  {en:"colour", fr:"la couleur", fr_phon:"la koo-LUR", cat:"adjectives", gender:"f", note:"noun, not an adjective"},
  {en:"white", fr:"blanc", fr_phon:"BLAHN", cat:"adjectives", note:"f: blanche"},
  {en:"black", fr:"noir", fr_phon:"NWAR", cat:"adjectives", note:"f: noire"},
  {en:"red", fr:"rouge", fr_phon:"ROOZH", cat:"adjectives", note:"same m/f"},
  {en:"yellow", fr:"jaune", fr_phon:"ZHOHN", cat:"adjectives", note:"same m/f"},
  {en:"green", fr:"vert", fr_phon:"VAIR", cat:"adjectives", note:"f: verte"},
  {en:"grey", fr:"gris", fr_phon:"GREE", cat:"adjectives", note:"f: grise"},
  {en:"light blue", fr:"bleu clair", fr_phon:"bluh KLAIR", cat:"adjectives", note:"invariable"},
  {en:"dark blue", fr:"bleu foncé", fr_phon:"bluh fohn-SAY", cat:"adjectives", note:"invariable"},
  {en:"see", fr:"voir", fr_phon:"VWAR", cat:"adjectives", note:"source mislabels — verb 'to see'"},
  {en:"think", fr:"penser", fr_phon:"pahn-SAY", cat:"adjectives", note:"source mislabels — verb 'to think'"},
  {en:"lay down", fr:"s'allonger", fr_phon:"sa-lohn-ZHAY", cat:"adjectives", note:"source mislabels — verb"},
  {en:"sleep", fr:"dormir", fr_phon:"dor-MEER", cat:"adjectives", note:"source mislabels — verb"},
  {en:"good", fr:"bon", fr_phon:"BOHN", cat:"adjectives", note:"f: bonne"},
  {en:"bad", fr:"mauvais", fr_phon:"moh-VEH", cat:"adjectives", note:"f: mauvaise"},
  {en:"beautiful", fr:"beau", fr_phon:"BOH", cat:"adjectives", note:"f: belle"},
  {en:"cute", fr:"mignon", fr_phon:"mee-NYOHN", cat:"adjectives", note:"f: mignonne"},
  {en:"big", fr:"grand", fr_phon:"GRAHN", cat:"adjectives", note:"f: grande"},
  {en:"small ", fr:"petit", fr_phon:"puh-TEE", cat:"adjectives", note:"f: petite"},
  {en:"tall", fr:"grand", fr_phon:"GRAHN", cat:"adjectives", note:"f: grande"},
  {en:"short (height) ", fr:"petit", fr_phon:"puh-TEE", cat:"adjectives", note:"f: petite"},
  {en:"long ", fr:"long", fr_phon:"LOHN", cat:"adjectives", note:"f: longue"},
  {en:"short (length)", fr:"court", fr_phon:"KOOR", cat:"adjectives", note:"f: courte"},
  {en:"wide ", fr:"large", fr_phon:"LARZH", cat:"adjectives", note:"same m/f"},
  {en:"narrow ", fr:"étroit", fr_phon:"ay-TRWA", cat:"adjectives", note:"f: étroite"},
  {en:"heavy", fr:"lourd", fr_phon:"LOOR", cat:"adjectives", note:"f: lourde"},
  {en:"light (weight)", fr:"léger", fr_phon:"lay-ZHAY", cat:"adjectives", note:"f: légère"},
  {en:"hot ", fr:"chaud", fr_phon:"SHOH", cat:"adjectives", note:"f: chaude"},
  {en:"cold", fr:"froid", fr_phon:"FRWA", cat:"adjectives", note:"f: froide"},
  {en:"warm", fr:"tiède", fr_phon:"TYED", cat:"adjectives", note:"same m/f"},
  {en:"fast", fr:"rapide", fr_phon:"ra-PEED", cat:"adjectives", note:"same m/f"},
  {en:"slow", fr:"lent", fr_phon:"LAHN", cat:"adjectives", note:"f: lente"},
  {en:"easy", fr:"facile", fr_phon:"fa-SEEL", cat:"adjectives", note:"same m/f"},
  {en:"difficult", fr:"difficile", fr_phon:"dee-fee-SEEL", cat:"adjectives", note:"same m/f"},
  {en:"fun", fr:"amusant", fr_phon:"a-mew-ZAHN", cat:"adjectives", note:"f: amusante"},
  {en:"boring", fr:"ennuyeux", fr_phon:"ahn-nwee-YUH", cat:"adjectives", note:"f: ennuyeuse"},
  {en:"interesting", fr:"intéressant", fr_phon:"an-tay-reh-SAHN", cat:"adjectives", note:"f: intéressante"},
  {en:"tired", fr:"fatigué", fr_phon:"fa-tee-GAY", cat:"adjectives", note:"f: fatiguée"},
  {en:"hungry", fr:"affamé", fr_phon:"a-fa-MAY", cat:"adjectives", note:"usually 'avoir faim' (j'ai faim)"},
  {en:"thirsty", fr:"assoiffé", fr_phon:"a-swa-FAY", cat:"adjectives", note:"usually 'avoir soif'"},
  {en:"full (after eating)", fr:"rassasié", fr_phon:"ra-sa-ZYAY", cat:"adjectives", note:"f: rassasiée"},
  {en:"expensive", fr:"cher", fr_phon:"SHAIR", cat:"adjectives", note:"f: chère"},
  {en:"cheap", fr:"bon marché", fr_phon:"bohn mar-SHAY", cat:"adjectives", note:"invariable; pas cher"},
  {en:"near", fr:"proche", fr_phon:"PROSH", cat:"adjectives", note:"près de"},
  {en:"far", fr:"loin", fr_phon:"LWAN", cat:"adjectives", note:"loin de"},
  {en:"new ", fr:"nouveau", fr_phon:"noo-VOH", cat:"adjectives", note:"f: nouvelle"},
  {en:"old", fr:"vieux", fr_phon:"VYUH", cat:"adjectives", note:"f: vieille"},
  {en:"clean ", fr:"propre", fr_phon:"PROP-ruh", cat:"adjectives", note:"same m/f"},
  {en:"dirty ", fr:"sale", fr_phon:"SAL", cat:"adjectives", note:"same m/f"},
  {en:"quiet", fr:"calme", fr_phon:"KALM", cat:"adjectives", note:"same m/f"},
  {en:"noisy", fr:"bruyant", fr_phon:"brwee-YAHN", cat:"adjectives", note:"f: bruyante"},
  {en:"safe", fr:"sûr", fr_phon:"SEWR", cat:"adjectives", note:"f: sûre"},
  {en:"dangerous", fr:"dangereux", fr_phon:"dahn-zhuh-RUH", cat:"adjectives", note:"f: dangereuse"},
  {en:"correct", fr:"correct", fr_phon:"koh-REKT", cat:"adjectives", note:"f: correcte; juste"},
  {en:"wrong", fr:"faux", fr_phon:"FOH", cat:"adjectives", note:"f: fausse"},
  {en:"same", fr:"même", fr_phon:"MEM", cat:"adjectives", note:"same m/f"},
  {en:"different", fr:"différent", fr_phon:"dee-fay-RAHN", cat:"adjectives", note:"f: différente"},
  {en:"enough", fr:"assez", fr_phon:"a-SAY", cat:"adjectives", note:"assez de + noun"},
  {en:"more", fr:"plus", fr_phon:"PLEW", cat:"adjectives", note:"plus de + noun"},
  {en:"less", fr:"moins", fr_phon:"MWAN", cat:"adjectives", note:"moins de + noun"},
  {en:"a lot / very", fr:"beaucoup / très", fr_phon:"boh-KOO / TREH", cat:"adjectives", note:"beaucoup (a lot), très (very)"},
  {en:"a little", fr:"un peu", fr_phon:"uhn PUH", cat:"adjectives"},
  {en:"full (not empty)", fr:"plein", fr_phon:"PLAN", cat:"adjectives", note:"f: pleine"},

  // ── food (65) ──
  {en:"delicious", fr:"délicieux", fr_phon:"day-lee-SYUH", cat:"food", note:"f: délicieuse"},
  {en:"spicy", fr:"épicé", fr_phon:"ay-pee-SAY", cat:"food", note:"f: épicée; piquant"},
  {en:"not spicy", fr:"pas épicé", fr_phon:"pa zay-pee-SAY", cat:"food"},
  {en:"sweet", fr:"sucré", fr_phon:"sew-KRAY", cat:"food", note:"f: sucrée"},
  {en:"sour", fr:"acide", fr_phon:"a-SEED", cat:"food", note:"aigre"},
  {en:"salty", fr:"salé", fr_phon:"sa-LAY", cat:"food", note:"f: salée"},
  {en:"bitter", fr:"amer", fr_phon:"a-MAIR", cat:"food", note:"f: amère"},
  {en:"rice", fr:"le riz", fr_phon:"luh REE", cat:"food", gender:"m"},
  {en:"sticky rice", fr:"le riz gluant", fr_phon:"luh ree glew-AHN", cat:"food", gender:"m"},
  {en:"fried rice", fr:"le riz frit", fr_phon:"luh ree FREE", cat:"food", gender:"m"},
  {en:"noodles", fr:"les nouilles", fr_phon:"lay NOO-yuh", cat:"food", gender:"f", note:"plural"},
  {en:"pad thai", fr:"le pad thaï", fr_phon:"luh pad-TY", cat:"food", gender:"m"},
  {en:"tom yum soup", fr:"la soupe tom yum", fr_phon:"la soop tom-YUM", cat:"food", gender:"f"},
  {en:"green curry", fr:"le curry vert", fr_phon:"luh kew-ree VAIR", cat:"food", gender:"m"},
  {en:"red curry", fr:"le curry rouge", fr_phon:"luh kew-ree ROOZH", cat:"food", gender:"m"},
  {en:"papaya salad", fr:"la salade de papaye", fr_phon:"la sa-lad duh pa-PY", cat:"food", gender:"f"},
  {en:"mango sticky rice", fr:"le riz gluant à la mangue", fr_phon:"luh ree glew-ahn a la MAHNG", cat:"food", gender:"m"},
  {en:"spring rolls", fr:"les rouleaux de printemps", fr_phon:"lay roo-loh duh pran-TAHN", cat:"food", gender:"m", note:"plural"},
  {en:"satay", fr:"les brochettes satay", fr_phon:"lay bro-shet sa-TAY", cat:"food", gender:"f", note:"plural"},
  {en:"chicken", fr:"le poulet", fr_phon:"luh poo-LEH", cat:"food", gender:"m"},
  {en:"pork", fr:"le porc", fr_phon:"luh POR", cat:"food", gender:"m"},
  {en:"beef", fr:"le bœuf", fr_phon:"luh BUHF", cat:"food", gender:"m"},
  {en:"fish", fr:"le poisson", fr_phon:"luh pwa-SOHN", cat:"food", gender:"m"},
  {en:"shrimp", fr:"la crevette", fr_phon:"la kruh-VET", cat:"food", gender:"f"},
  {en:"crab", fr:"le crabe", fr_phon:"luh KRAB", cat:"food", gender:"m"},
  {en:"squid", fr:"le calmar", fr_phon:"luh kal-MAR", cat:"food", gender:"m"},
  {en:"egg", fr:"l'œuf", fr_phon:"LUHF", cat:"food", gender:"m"},
  {en:"tofu", fr:"le tofu", fr_phon:"luh toh-FEW", cat:"food", gender:"m"},
  {en:"vegetables", fr:"les légumes", fr_phon:"lay lay-GEWM", cat:"food", gender:"m", note:"plural"},
  {en:"garlic", fr:"l'ail", fr_phon:"LY", cat:"food", gender:"m"},
  {en:"onion", fr:"l'oignon", fr_phon:"loh-NYOHN", cat:"food", gender:"m"},
  {en:"chili", fr:"le piment", fr_phon:"luh pee-MAHN", cat:"food", gender:"m"},
  {en:"ginger", fr:"le gingembre", fr_phon:"luh zhan-ZHAHM-bruh", cat:"food", gender:"m"},
  {en:"lemongrass", fr:"la citronnelle", fr_phon:"la see-troh-NEL", cat:"food", gender:"f"},
  {en:"coconut milk", fr:"le lait de coco", fr_phon:"luh leh duh ko-KOH", cat:"food", gender:"m"},
  {en:"fish sauce", fr:"la sauce de poisson", fr_phon:"la sohss duh pwa-SOHN", cat:"food", gender:"f", note:"nuoc-mâm"},
  {en:"soy sauce", fr:"la sauce soja", fr_phon:"la sohss soh-ZHA", cat:"food", gender:"f"},
  {en:"sugar", fr:"le sucre", fr_phon:"luh SEW-kruh", cat:"food", gender:"m"},
  {en:"salt", fr:"le sel", fr_phon:"luh SEL", cat:"food", gender:"m"},
  {en:"lime", fr:"le citron vert", fr_phon:"luh see-trohn VAIR", cat:"food", gender:"m"},
  {en:"mango", fr:"la mangue", fr_phon:"la MAHNG", cat:"food", gender:"f"},
  {en:"banana", fr:"la banane", fr_phon:"la ba-NAN", cat:"food", gender:"f"},
  {en:"pineapple", fr:"l'ananas", fr_phon:"la-na-NA", cat:"food", gender:"m"},
  {en:"watermelon", fr:"la pastèque", fr_phon:"la pas-TEK", cat:"food", gender:"f"},
  {en:"durian", fr:"le durian", fr_phon:"luh dew-ree-AHN", cat:"food", gender:"m"},
  {en:"coconut", fr:"la noix de coco", fr_phon:"la nwa duh ko-KOH", cat:"food", gender:"f"},
  {en:"bread", fr:"le pain", fr_phon:"luh PAN", cat:"food", gender:"m"},
  {en:"soup", fr:"la soupe", fr_phon:"la SOOP", cat:"food", gender:"f"},
  {en:"stir-fried", fr:"sauté", fr_phon:"soh-TAY", cat:"food", note:"f: sautée; cooking method"},
  {en:"deep-fried", fr:"frit", fr_phon:"FREE", cat:"food", note:"f: frite"},
  {en:"steamed", fr:"à la vapeur", fr_phon:"a la va-PUR", cat:"food"},
  {en:"grilled", fr:"grillé", fr_phon:"gree-YAY", cat:"food", note:"f: grillée"},
  {en:"fried egg", fr:"l'œuf au plat", fr_phon:"luhf oh PLA", cat:"food", gender:"m"},
  {en:"omelette", fr:"l'omelette", fr_phon:"lom-LET", cat:"food", gender:"f"},
  {en:"papaya", fr:"la papaye", fr_phon:"la pa-PY", cat:"food", gender:"f"},
  {en:"water", fr:"l'eau", fr_phon:"LOH", cat:"food", gender:"f"},
  {en:"coffee", fr:"le café", fr_phon:"luh ka-FAY", cat:"food", gender:"m"},
  {en:"tea", fr:"le thé", fr_phon:"luh TAY", cat:"food", gender:"m"},
  {en:"beer", fr:"la bière", fr_phon:"la BYAIR", cat:"food", gender:"f"},
  {en:"wine", fr:"le vin", fr_phon:"luh VAN", cat:"food", gender:"m"},
  {en:"juice", fr:"le jus", fr_phon:"luh ZHEW", cat:"food", gender:"m"},
  {en:"coconut water", fr:"l'eau de coco", fr_phon:"loh duh ko-KOH", cat:"food", gender:"f"},
  {en:"soda", fr:"le soda", fr_phon:"luh soh-DA", cat:"food", gender:"m"},
  {en:"milk", fr:"le lait", fr_phon:"luh LEH", cat:"food", gender:"m"},
  {en:"ice", fr:"la glace", fr_phon:"la GLASS", cat:"food", gender:"f", note:"les glaçons = ice cubes"},

  // ── body (20) ──
  {en:"head", fr:"la tête", fr_phon:"la TET", cat:"body", gender:"f"},
  {en:"face", fr:"le visage", fr_phon:"luh vee-ZAZH", cat:"body", gender:"m"},
  {en:"eye", fr:"l'œil", fr_phon:"LUH-yuh", cat:"body", gender:"m", note:"plural: les yeux"},
  {en:"ear", fr:"l'oreille", fr_phon:"lo-RAY", cat:"body", gender:"f"},
  {en:"nose", fr:"le nez", fr_phon:"luh NAY", cat:"body", gender:"m"},
  {en:"mouth", fr:"la bouche", fr_phon:"la BOOSH", cat:"body", gender:"f"},
  {en:"tooth", fr:"la dent", fr_phon:"la DAHN", cat:"body", gender:"f"},
  {en:"hair", fr:"les cheveux", fr_phon:"lay shuh-VUH", cat:"body", gender:"m", note:"plural"},
  {en:"neck", fr:"le cou", fr_phon:"luh KOO", cat:"body", gender:"m"},
  {en:"shoulder", fr:"l'épaule", fr_phon:"lay-POHL", cat:"body", gender:"f"},
  {en:"arm", fr:"le bras", fr_phon:"luh BRA", cat:"body", gender:"m"},
  {en:"hand", fr:"la main", fr_phon:"la MAN", cat:"body", gender:"f"},
  {en:"finger", fr:"le doigt", fr_phon:"luh DWA", cat:"body", gender:"m"},
  {en:"chest", fr:"la poitrine", fr_phon:"la pwa-TREEN", cat:"body", gender:"f"},
  {en:"stomach", fr:"le ventre", fr_phon:"luh VAHN-truh", cat:"body", gender:"m", note:"l'estomac (organ)"},
  {en:"back", fr:"le dos", fr_phon:"luh DOH", cat:"body", gender:"m"},
  {en:"leg", fr:"la jambe", fr_phon:"la ZHAHMB", cat:"body", gender:"f"},
  {en:"knee", fr:"le genou", fr_phon:"luh zhuh-NOO", cat:"body", gender:"m"},
  {en:"foot", fr:"le pied", fr_phon:"luh PYAY", cat:"body", gender:"m"},
  {en:"heart", fr:"le cœur", fr_phon:"luh KUR", cat:"body", gender:"m"},

  // ── health (20) ──
  {en:"doctor", fr:"le médecin", fr_phon:"luh mayd-SAN", cat:"health", gender:"m", note:"le/la médecin"},
  {en:"nurse", fr:"l'infirmier", fr_phon:"lan-feer-MYAY", cat:"health", gender:"m", note:"f: l'infirmière"},
  {en:"medicine", fr:"le médicament", fr_phon:"luh may-dee-ka-MAHN", cat:"health", gender:"m"},
  {en:"sick / unwell", fr:"malade", fr_phon:"ma-LAD", cat:"health", note:"same m/f"},
  {en:"hurt / pain", fr:"la douleur", fr_phon:"la doo-LUR", cat:"health", gender:"f", note:"avoir mal"},
  {en:"headache", fr:"le mal de tête", fr_phon:"luh mal duh TET", cat:"health", gender:"m"},
  {en:"stomach ache", fr:"le mal de ventre", fr_phon:"luh mal duh VAHN-truh", cat:"health", gender:"m"},
  {en:"fever", fr:"la fièvre", fr_phon:"la FYEV-ruh", cat:"health", gender:"f"},
  {en:"cold (illness)", fr:"le rhume", fr_phon:"luh REWM", cat:"health", gender:"m"},
  {en:"cough", fr:"la toux", fr_phon:"la TOO", cat:"health", gender:"f"},
  {en:"allergy", fr:"l'allergie", fr_phon:"la-lair-ZHEE", cat:"health", gender:"f"},
  {en:"emergency", fr:"l'urgence", fr_phon:"lewr-ZHAHNS", cat:"health", gender:"f"},
  {en:"ambulance", fr:"l'ambulance", fr_phon:"lahn-bew-LAHNS", cat:"health", gender:"f"},
  {en:"blood", fr:"le sang", fr_phon:"luh SAHN", cat:"health", gender:"m"},
  {en:"dizzy", fr:"étourdi", fr_phon:"ay-toor-DEE", cat:"health", note:"f: étourdie; avoir la tête qui tourne"},
  {en:"I feel unwell", fr:"Je ne me sens pas bien", fr_phon:"zhuh nuh muh sahn pa BYAN", cat:"health"},
  {en:"call a doctor", fr:"appeler un médecin", fr_phon:"ap-lay uhn mayd-SAN", cat:"health"},
  {en:"pharmacy", fr:"la pharmacie", fr_phon:"la far-ma-SEE", cat:"health", gender:"f"},
  {en:"tired / exhausted", fr:"épuisé", fr_phon:"ay-pwee-ZAY", cat:"health", note:"f: épuisée"},
  {en:"broken / injured", fr:"blessé", fr_phon:"bleh-SAY", cat:"health", note:"f: blessée; cassé = broken"},

  // ── emotions (15) — adjectives ──
  {en:"happy", fr:"heureux", fr_phon:"uh-RUH", cat:"emotions", note:"f: heureuse; content"},
  {en:"sad", fr:"triste", fr_phon:"TREEST", cat:"emotions", note:"same m/f"},
  {en:"angry", fr:"en colère", fr_phon:"ahn ko-LAIR", cat:"emotions", note:"fâché"},
  {en:"scared", fr:"effrayé", fr_phon:"eh-freh-YAY", cat:"emotions", note:"avoir peur"},
  {en:"lonely", fr:"seul", fr_phon:"SUHL", cat:"emotions", note:"f: seule"},
  {en:"stressed", fr:"stressé", fr_phon:"streh-SAY", cat:"emotions", note:"f: stressée"},
  {en:"relaxed", fr:"détendu", fr_phon:"day-tahn-DEW", cat:"emotions", note:"f: détendue"},
  {en:"proud", fr:"fier", fr_phon:"FYAIR", cat:"emotions", note:"f: fière"},
  {en:"embarrassed", fr:"gêné", fr_phon:"zheh-NAY", cat:"emotions", note:"f: gênée"},
  {en:"jealous", fr:"jaloux", fr_phon:"zha-LOO", cat:"emotions", note:"f: jalouse"},
  {en:"confused", fr:"perdu", fr_phon:"pair-DEW", cat:"emotions", note:"f: perdue; confus"},
  {en:"excited", fr:"excité", fr_phon:"ek-see-TAY", cat:"emotions", note:"f: excitée; enthousiaste"},
  {en:"nervous", fr:"nerveux", fr_phon:"nair-VUH", cat:"emotions", note:"f: nerveuse"},
  {en:"grateful", fr:"reconnaissant", fr_phon:"ruh-koh-neh-SAHN", cat:"emotions", note:"f: reconnaissante"},
  {en:"bored", fr:"ennuyé", fr_phon:"ahn-nwee-YAY", cat:"emotions", note:"s'ennuyer = to be bored"},

  // ── animals (20) ──
  {en:"dog", fr:"le chien", fr_phon:"luh SHYAN", cat:"animals", gender:"m", note:"f: la chienne"},
  {en:"cat", fr:"le chat", fr_phon:"luh SHA", cat:"animals", gender:"m", note:"f: la chatte"},
  {en:"elephant", fr:"l'éléphant", fr_phon:"lay-lay-FAHN", cat:"animals", gender:"m"},
  {en:"monkey", fr:"le singe", fr_phon:"luh SANZH", cat:"animals", gender:"m"},
  {en:"bird", fr:"l'oiseau", fr_phon:"lwa-ZOH", cat:"animals", gender:"m"},
  {en:"snake", fr:"le serpent", fr_phon:"luh sair-PAHN", cat:"animals", gender:"m"},
  {en:"tiger", fr:"le tigre", fr_phon:"luh TEE-gruh", cat:"animals", gender:"m"},
  {en:"horse", fr:"le cheval", fr_phon:"luh shuh-VAL", cat:"animals", gender:"m", note:"plural: chevaux"},
  {en:"cow", fr:"la vache", fr_phon:"la VASH", cat:"animals", gender:"f"},
  {en:"pig", fr:"le cochon", fr_phon:"luh ko-SHOHN", cat:"animals", gender:"m"},
  {en:"duck", fr:"le canard", fr_phon:"luh ka-NAR", cat:"animals", gender:"m"},
  {en:"rabbit", fr:"le lapin", fr_phon:"luh la-PAN", cat:"animals", gender:"m"},
  {en:"frog", fr:"la grenouille", fr_phon:"la gruh-NOO-yuh", cat:"animals", gender:"f"},
  {en:"mosquito", fr:"le moustique", fr_phon:"luh moos-TEEK", cat:"animals", gender:"m"},
  {en:"ant", fr:"la fourmi", fr_phon:"la foor-MEE", cat:"animals", gender:"f"},
  {en:"butterfly", fr:"le papillon", fr_phon:"luh pa-pee-YOHN", cat:"animals", gender:"m"},
  {en:"crocodile", fr:"le crocodile", fr_phon:"luh kro-ko-DEEL", cat:"animals", gender:"m"},
  {en:"fish", fr:"le poisson", fr_phon:"luh pwa-SOHN", cat:"animals", gender:"m"},
  {en:"chicken (animal)", fr:"le poulet", fr_phon:"luh poo-LEH", cat:"animals", gender:"m", note:"la poule = hen"},
  {en:"buffalo", fr:"le buffle", fr_phon:"luh BEW-fluh", cat:"animals", gender:"m"},

  // ── places (21) ──
  {en:"7-11 / convenience store", fr:"la supérette", fr_phon:"la sew-pay-RET", cat:"places", gender:"f"},
  {en:"bank", fr:"la banque", fr_phon:"la BAHNK", cat:"places", gender:"f"},
  {en:"shop", fr:"le magasin", fr_phon:"luh ma-ga-ZAN", cat:"places", gender:"m"},
  {en:"school", fr:"l'école", fr_phon:"lay-KOL", cat:"places", gender:"f"},
  {en:"restaurant", fr:"le restaurant", fr_phon:"luh res-toh-RAHN", cat:"places", gender:"m"},
  {en:"village", fr:"le village", fr_phon:"luh vee-LAZH", cat:"places", gender:"m"},
  {en:"police station", fr:"le commissariat", fr_phon:"luh ko-mee-sa-RYA", cat:"places", gender:"m"},
  {en:"railway station", fr:"la gare", fr_phon:"la GAR", cat:"places", gender:"f"},
  {en:"bar", fr:"le bar", fr_phon:"luh BAR", cat:"places", gender:"m"},
  {en:"hotel", fr:"l'hôtel", fr_phon:"loh-TEL", cat:"places", gender:"m"},
  {en:"cinema", fr:"le cinéma", fr_phon:"luh see-nay-MA", cat:"places", gender:"m"},
  {en:"market", fr:"le marché", fr_phon:"luh mar-SHAY", cat:"places", gender:"m"},
  {en:"post office", fr:"la poste", fr_phon:"la POST", cat:"places", gender:"f"},
  {en:"hospital", fr:"l'hôpital", fr_phon:"loh-pee-TAL", cat:"places", gender:"m"},
  {en:"coffee shop", fr:"le café", fr_phon:"luh ka-FAY", cat:"places", gender:"m"},
  {en:"embassy", fr:"l'ambassade", fr_phon:"lahn-ba-SAD", cat:"places", gender:"f"},
  {en:"house / home", fr:"la maison", fr_phon:"la meh-ZOHN", cat:"places", gender:"f"},
  {en:"district office", fr:"la mairie", fr_phon:"la meh-REE", cat:"places", gender:"f", note:"town hall"},
  {en:"airport", fr:"l'aéroport", fr_phon:"la-ay-roh-POR", cat:"places", gender:"m"},
  {en:"department store", fr:"le grand magasin", fr_phon:"luh grahn ma-ga-ZAN", cat:"places", gender:"m", note:"replaced Thai-specific 'Central'"},
  {en:"shopping mall", fr:"le centre commercial", fr_phon:"luh sahn-truh ko-mair-SYAL", cat:"places", gender:"m", note:"replaced Thai-specific 'Jungceylon'"},

  // ── transport (12) ──
  {en:"car", fr:"la voiture", fr_phon:"la vwa-TEWR", cat:"transport", gender:"f"},
  {en:"motorbike", fr:"la moto", fr_phon:"la mo-TOH", cat:"transport", gender:"f"},
  {en:"bus", fr:"le bus", fr_phon:"luh BEWSS", cat:"transport", gender:"m"},
  {en:"train", fr:"le train", fr_phon:"luh TRAN", cat:"transport", gender:"m"},
  {en:"taxi", fr:"le taxi", fr_phon:"luh tak-SEE", cat:"transport", gender:"m"},
  {en:"tuk-tuk", fr:"le tuk-tuk", fr_phon:"luh took-TOOK", cat:"transport", gender:"m"},
  {en:"boat", fr:"le bateau", fr_phon:"luh ba-TOH", cat:"transport", gender:"m"},
  {en:"plane", fr:"l'avion", fr_phon:"la-VYOHN", cat:"transport", gender:"m"},
  {en:"bicycle", fr:"le vélo", fr_phon:"luh vay-LOH", cat:"transport", gender:"m"},
  {en:"subway / MRT", fr:"le métro", fr_phon:"luh may-TROH", cat:"transport", gender:"m"},
  {en:"ticket", fr:"le billet", fr_phon:"luh bee-YEH", cat:"transport", gender:"m", note:"le ticket"},
  {en:"road / street", fr:"la rue", fr_phon:"la REW", cat:"transport", gender:"f", note:"la route"},

  // ── directions (10) ──
  {en:"left", fr:"gauche", fr_phon:"GOHSH", cat:"directions", note:"à gauche = on/to the left"},
  {en:"right", fr:"droite", fr_phon:"DRWAT", cat:"directions", note:"à droite = on/to the right"},
  {en:"straight ahead", fr:"tout droit", fr_phon:"too DRWA", cat:"directions"},
  {en:"turn", fr:"tourner", fr_phon:"toor-NAY", cat:"directions"},
  {en:"north", fr:"le nord", fr_phon:"luh NOR", cat:"directions", gender:"m"},
  {en:"south", fr:"le sud", fr_phon:"luh SEWD", cat:"directions", gender:"m"},
  {en:"east", fr:"l'est", fr_phon:"LEST", cat:"directions", gender:"m"},
  {en:"west", fr:"l'ouest", fr_phon:"LWEST", cat:"directions", gender:"m"},
  {en:"near", fr:"près", fr_phon:"PREH", cat:"directions", note:"près de"},
  {en:"far", fr:"loin", fr_phon:"LWAN", cat:"directions", note:"loin de"},

  // ── home (15) ──
  {en:"room", fr:"la pièce", fr_phon:"la PYESS", cat:"home", gender:"f"},
  {en:"bedroom", fr:"la chambre", fr_phon:"la SHAHM-bruh", cat:"home", gender:"f"},
  {en:"bathroom", fr:"la salle de bain", fr_phon:"la sal duh BAN", cat:"home", gender:"f"},
  {en:"kitchen", fr:"la cuisine", fr_phon:"la kwee-ZEEN", cat:"home", gender:"f"},
  {en:"living room", fr:"le salon", fr_phon:"luh sa-LOHN", cat:"home", gender:"m"},
  {en:"door", fr:"la porte", fr_phon:"la PORT", cat:"home", gender:"f"},
  {en:"window", fr:"la fenêtre", fr_phon:"la fuh-NET-ruh", cat:"home", gender:"f"},
  {en:"table", fr:"la table", fr_phon:"la TAB-luh", cat:"home", gender:"f"},
  {en:"chair", fr:"la chaise", fr_phon:"la SHEZ", cat:"home", gender:"f"},
  {en:"bed", fr:"le lit", fr_phon:"luh LEE", cat:"home", gender:"m"},
  {en:"pillow", fr:"l'oreiller", fr_phon:"lo-reh-YAY", cat:"home", gender:"m"},
  {en:"air conditioning", fr:"la climatisation", fr_phon:"la klee-ma-tee-za-SYOHN", cat:"home", gender:"f", note:"la clim"},
  {en:"fan", fr:"le ventilateur", fr_phon:"luh vahn-tee-la-TUR", cat:"home", gender:"m"},
  {en:"television", fr:"la télévision", fr_phon:"la tay-lay-vee-ZYOHN", cat:"home", gender:"f", note:"la télé"},
  {en:"refrigerator", fr:"le réfrigérateur", fr_phon:"luh ray-free-zhay-ra-TUR", cat:"home", gender:"m", note:"le frigo"},

  // ── work (20) ──
  {en:"work", fr:"le travail", fr_phon:"luh tra-VY", cat:"work", gender:"m"},
  {en:"job / career", fr:"le métier", fr_phon:"luh may-TYAY", cat:"work", gender:"m", note:"la carrière"},
  {en:"boss", fr:"le patron", fr_phon:"luh pa-TROHN", cat:"work", gender:"m", note:"f: la patronne"},
  {en:"colleague", fr:"le collègue", fr_phon:"luh ko-LEG", cat:"work", gender:"mf", note:"le/la collègue"},
  {en:"meeting", fr:"la réunion", fr_phon:"la ray-ew-NYOHN", cat:"work", gender:"f"},
  {en:"computer", fr:"l'ordinateur", fr_phon:"lor-dee-na-TUR", cat:"work", gender:"m"},
  {en:"phone", fr:"le téléphone", fr_phon:"luh tay-lay-FON", cat:"work", gender:"m"},
  {en:"email", fr:"l'e-mail", fr_phon:"lee-MEL", cat:"work", gender:"m", note:"le courriel"},
  {en:"school", fr:"l'école", fr_phon:"lay-KOL", cat:"work", gender:"f"},
  {en:"teacher", fr:"le professeur", fr_phon:"luh pro-feh-SUR", cat:"work", gender:"m", note:"le/la prof"},
  {en:"student", fr:"l'étudiant", fr_phon:"lay-tew-DYAHN", cat:"work", gender:"m", note:"f: l'étudiante"},
  {en:"homework", fr:"les devoirs", fr_phon:"lay duh-VWAR", cat:"work", gender:"m", note:"plural"},
  {en:"exam / test", fr:"l'examen", fr_phon:"leg-za-MAN", cat:"work", gender:"m"},
  {en:"pass", fr:"réussir", fr_phon:"ray-ew-SEER", cat:"work", note:"verb: to pass/succeed"},
  {en:"fail", fr:"échouer", fr_phon:"ay-shoo-AY", cat:"work", note:"rater = to fail/miss"},
  {en:"salary", fr:"le salaire", fr_phon:"luh sa-LAIR", cat:"work", gender:"m"},
  {en:"holiday / day off", fr:"le jour de congé", fr_phon:"luh zhoor duh kohn-ZHAY", cat:"work", gender:"m", note:"les vacances = holidays"},
  {en:"busy", fr:"occupé", fr_phon:"o-kew-PAY", cat:"work", note:"f: occupée"},
  {en:"free (not busy)", fr:"libre", fr_phon:"LEE-bruh", cat:"work", note:"same m/f"},
  {en:"project", fr:"le projet", fr_phon:"luh pro-ZHEH", cat:"work", gender:"m"},

  // ── shopping (18) ──
  {en:"kilogram", fr:"le kilo", fr_phon:"luh kee-LOH", cat:"shopping", gender:"m"},
  {en:"100 grams", fr:"cent grammes", fr_phon:"sahn GRAM", cat:"shopping"},
  {en:"litre", fr:"le litre", fr_phon:"luh LEE-truh", cat:"shopping", gender:"m"},
  {en:"half", fr:"la moitié", fr_phon:"la mwa-TYAY", cat:"shopping", gender:"f", note:"demi"},
  {en:"rice", fr:"le riz", fr_phon:"luh REE", cat:"shopping", gender:"m"},
  {en:"milk", fr:"le lait", fr_phon:"luh LEH", cat:"shopping", gender:"m"},
  {en:"orange juice", fr:"le jus d'orange", fr_phon:"luh zhew do-RAHNZH", cat:"shopping", gender:"m"},
  {en:"apple juice", fr:"le jus de pomme", fr_phon:"luh zhew duh POM", cat:"shopping", gender:"m"},
  {en:"tea", fr:"le thé", fr_phon:"luh TAY", cat:"shopping", gender:"m"},
  {en:"beef", fr:"le bœuf", fr_phon:"luh BUHF", cat:"shopping", gender:"m"},
  {en:"pork", fr:"le porc", fr_phon:"luh POR", cat:"shopping", gender:"m"},
  {en:"chicken", fr:"le poulet", fr_phon:"luh poo-LEH", cat:"shopping", gender:"m"},
  {en:"sugar", fr:"le sucre", fr_phon:"luh SEW-kruh", cat:"shopping", gender:"m"},
  {en:"cooking oil", fr:"l'huile", fr_phon:"LWEEL", cat:"shopping", gender:"f", note:"l'huile de cuisine"},
  {en:"half a kilo of beef", fr:"un demi-kilo de bœuf", fr_phon:"uhn duh-mee-kee-loh duh BUHF", cat:"shopping"},
  {en:"150 grams of chicken", fr:"cent cinquante grammes de poulet", fr_phon:"sahn san-kahnt gram duh poo-LEH", cat:"shopping"},
  {en:"a litre of milk", fr:"un litre de lait", fr_phon:"uhn lee-truh duh LEH", cat:"shopping"},
  {en:"3 bottles of cooking oil", fr:"trois bouteilles d'huile", fr_phon:"trwa boo-tay DWEEL", cat:"shopping"},

  // ── clothing (15) ──
  {en:"shirt", fr:"la chemise", fr_phon:"la shuh-MEEZ", cat:"clothing", gender:"f"},
  {en:"trousers / pants", fr:"le pantalon", fr_phon:"luh pahn-ta-LOHN", cat:"clothing", gender:"m"},
  {en:"dress", fr:"la robe", fr_phon:"la ROB", cat:"clothing", gender:"f"},
  {en:"skirt", fr:"la jupe", fr_phon:"la ZHEWP", cat:"clothing", gender:"f"},
  {en:"shoes", fr:"les chaussures", fr_phon:"lay shoh-SEWR", cat:"clothing", gender:"f", note:"plural"},
  {en:"sandals", fr:"les sandales", fr_phon:"lay sahn-DAL", cat:"clothing", gender:"f", note:"plural"},
  {en:"hat", fr:"le chapeau", fr_phon:"luh sha-POH", cat:"clothing", gender:"m"},
  {en:"glasses", fr:"les lunettes", fr_phon:"lay lew-NET", cat:"clothing", gender:"f", note:"plural"},
  {en:"bag", fr:"le sac", fr_phon:"luh SAK", cat:"clothing", gender:"m"},
  {en:"watch", fr:"la montre", fr_phon:"la MOHN-truh", cat:"clothing", gender:"f"},
  {en:"ring", fr:"la bague", fr_phon:"la BAG", cat:"clothing", gender:"f"},
  {en:"necklace", fr:"le collier", fr_phon:"luh ko-LYAY", cat:"clothing", gender:"m"},
  {en:"clothes", fr:"les vêtements", fr_phon:"lay vet-MAHN", cat:"clothing", gender:"m", note:"plural"},
  {en:"jacket / coat", fr:"la veste", fr_phon:"la VEST", cat:"clothing", gender:"f", note:"le manteau = coat"},
  {en:"underwear", fr:"les sous-vêtements", fr_phon:"lay soo-vet-MAHN", cat:"clothing", gender:"m", note:"plural"},

  // ── nature (15) ──
  {en:"sun", fr:"le soleil", fr_phon:"luh so-LAY", cat:"nature", gender:"m"},
  {en:"moon", fr:"la lune", fr_phon:"la LEWN", cat:"nature", gender:"f"},
  {en:"star", fr:"l'étoile", fr_phon:"lay-TWAL", cat:"nature", gender:"f"},
  {en:"sky", fr:"le ciel", fr_phon:"luh SYEL", cat:"nature", gender:"m"},
  {en:"cloud", fr:"le nuage", fr_phon:"luh new-AZH", cat:"nature", gender:"m"},
  {en:"rain", fr:"la pluie", fr_phon:"la PLWEE", cat:"nature", gender:"f"},
  {en:"wind", fr:"le vent", fr_phon:"luh VAHN", cat:"nature", gender:"m"},
  {en:"mountain", fr:"la montagne", fr_phon:"la mohn-TAN-yuh", cat:"nature", gender:"f"},
  {en:"river", fr:"la rivière", fr_phon:"la ree-VYAIR", cat:"nature", gender:"f", note:"le fleuve = river to sea"},
  {en:"sea / ocean", fr:"la mer", fr_phon:"la MAIR", cat:"nature", gender:"f", note:"l'océan (m)"},
  {en:"beach", fr:"la plage", fr_phon:"la PLAZH", cat:"nature", gender:"f"},
  {en:"island", fr:"l'île", fr_phon:"LEEL", cat:"nature", gender:"f"},
  {en:"tree", fr:"l'arbre", fr_phon:"LAR-bruh", cat:"nature", gender:"m"},
  {en:"flower", fr:"la fleur", fr_phon:"la FLUR", cat:"nature", gender:"f"},
  {en:"grass", fr:"l'herbe", fr_phon:"LAIRB", cat:"nature", gender:"f"},

  // ── patterns (24) — grammar with sentences (tu register) ──
  {en:"have", fr:"avoir", fr_phon:"a-VWAR", cat:"patterns", note:"j'ai, tu as, il a…"},
  {en:"do not have", fr:"ne pas avoir", fr_phon:"nuh pa a-VWAR", cat:"patterns", note:"je n'ai pas"},
  {en:"Do you have? (question)", fr:"As-tu… ?", fr_phon:"a-TOO", cat:"patterns", note:"Est-ce que tu as… ?"},
  {en:"Does Peter have any friends?", fr:"Est-ce que Peter a des amis ?", fr_phon:"es-kuh pee-tair a day za-MEE", cat:"patterns"},
  {en:"Does Jane have a phone?", fr:"Est-ce que Jane a un téléphone ?", fr_phon:"es-kuh zhen a uhn tay-lay-FON", cat:"patterns"},
  {en:"Does this shop have any coffee?", fr:"Est-ce que ce magasin a du café ?", fr_phon:"es-kuh suh ma-ga-zan a dew ka-FAY", cat:"patterns"},
  {en:"Do we have any pizza?", fr:"Est-ce qu'on a de la pizza ?", fr_phon:"es-kohn a duh la peed-ZA", cat:"patterns"},
  {en:"Question tag (universal)", fr:"n'est-ce pas ?", fr_phon:"nes-PA", cat:"patterns", note:"one tag for all — add to end of a statement"},
  {en:"isn't it?", fr:"n'est-ce pas ?", fr_phon:"nes-PA", cat:"patterns"},
  {en:"aren't they?", fr:"n'est-ce pas ?", fr_phon:"nes-PA", cat:"patterns", note:"French uses one tag for all"},
  {en:"isn't he/she?", fr:"n'est-ce pas ?", fr_phon:"nes-PA", cat:"patterns"},
  {en:"Answer YES to tag question", fr:"Si", fr_phon:"SEE", cat:"patterns", note:"'si' = yes when contradicting a negative; otherwise 'oui'"},
  {en:"Answer NO to tag question", fr:"Non", fr_phon:"NOHN", cat:"patterns"},
  {en:"That is John, isn't it?", fr:"C'est John, n'est-ce pas ?", fr_phon:"say john nes-PA", cat:"patterns"},
  {en:"That is a table, isn't it?", fr:"C'est une table, n'est-ce pas ?", fr_phon:"say ewn tabl nes-PA", cat:"patterns"},
  {en:"He is not here, is he?", fr:"Il n'est pas là, n'est-ce pas ?", fr_phon:"eel nay pa la nes-PA", cat:"patterns"},
  {en:"It's not tall, is it?", fr:"Ce n'est pas grand, n'est-ce pas ?", fr_phon:"suh nay pa grahn nes-PA", cat:"patterns"},
  {en:"how many?", fr:"combien de… ?", fr_phon:"kohn-byan DUH", cat:"patterns"},
  {en:"How many cars do you have?", fr:"Combien de voitures as-tu ?", fr_phon:"kohn-byan duh vwa-tewr a-TOO", cat:"patterns"},
  {en:"How many friends does he have?", fr:"Combien d'amis a-t-il ?", fr_phon:"kohn-byan da-mee a-TEEL", cat:"patterns"},
  {en:"How many rooms does this house have?", fr:"Combien de pièces a cette maison ?", fr_phon:"kohn-byan duh pyess a set meh-ZOHN", cat:"patterns"},
  {en:"How many bottles of beer did he drink?", fr:"Combien de bières a-t-il bues ?", fr_phon:"kohn-byan duh byair a-teel BEW", cat:"patterns"},
  {en:"How many tickets will you buy?", fr:"Combien de billets vas-tu acheter ?", fr_phon:"kohn-byan duh bee-yeh va-too ash-TAY", cat:"patterns"},
  {en:"How many plates of rice do you want?", fr:"Combien d'assiettes de riz veux-tu ?", fr_phon:"kohn-byan da-syet duh ree vuh-TOO", cat:"patterns"},

  // ── grammar (56) — heavily reshaped from Thai; needs the most review ──
  {en:"Basic sentence", fr:"La phrase de base", fr_phon:"la frahz duh BAHZ", cat:"grammar", note:"French needs subject + conjugated verb"},
  {en:"Tense (context)", fr:"Le temps (contexte)", fr_phon:"luh TAHN", cat:"grammar", note:"French conjugates verbs for tense (unlike Thai)"},
  {en:"Future tense", fr:"Le futur", fr_phon:"luh few-TEWR", cat:"grammar", note:"aller + infinitif (je vais manger)"},
  {en:"Negative", fr:"La négation", fr_phon:"la nay-ga-SYOHN", cat:"grammar", note:"ne … pas around the verb"},
  {en:"Negative (want/would like)", fr:"Je ne veux pas", fr_phon:"zhuh nuh vuh PA", cat:"grammar"},
  {en:"Question", fr:"La question", fr_phon:"la kes-TYOHN", cat:"grammar", note:"Est-ce que… or invert verb + subject"},
  {en:"Here", fr:"ici", fr_phon:"ee-SEE", cat:"grammar"},
  {en:"There", fr:"là", fr_phon:"LA", cat:"grammar", note:"là-bas = over there"},
  {en:"Come here", fr:"Viens ici", fr_phon:"vyan zee-SEE", cat:"grammar", note:"tu form"},
  {en:"Go there", fr:"Vas-y", fr_phon:"va-ZEE", cat:"grammar", note:"tu form"},
  {en:"With (conjunction)", fr:"avec", fr_phon:"a-VEK", cat:"grammar"},
  {en:"And (conjunction)", fr:"et", fr_phon:"AY", cat:"grammar"},
  {en:"Polite particle (male)", fr:"s'il vous plaît / vous", fr_phon:"seel voo PLEH", cat:"grammar", note:"French has no gendered particles — politeness is via 'vous' + 's'il vous plaît'"},
  {en:"Polite particle (female)", fr:"s'il vous plaît / vous", fr_phon:"seel voo PLEH", cat:"grammar", note:"same as for males in French"},
  {en:"Want to", fr:"vouloir", fr_phon:"voo-LWAR", cat:"grammar", note:"je veux + infinitif"},
  {en:"Would like to", fr:"je voudrais", fr_phon:"zhuh voo-DREH", cat:"grammar", note:"+ infinitif (polite)"},
  {en:"Travelling verb (away)", fr:"y aller", fr_phon:"ee a-LAY", cat:"grammar", note:"aller = to go (away)"},
  {en:"Travelling verb (toward)", fr:"venir", fr_phon:"vuh-NEER", cat:"grammar", note:"to come (toward)"},
  {en:"Math: add", fr:"plus", fr_phon:"PLEWSS", cat:"grammar", note:"additionner; 2 + 2"},
  {en:"Math: subtract", fr:"moins", fr_phon:"MWAN", cat:"grammar", note:"soustraire"},
  {en:"Math: multiply", fr:"fois", fr_phon:"FWA", cat:"grammar", note:"multiplier; 2 × 3 = deux fois trois"},
  {en:"Math: divide", fr:"divisé par", fr_phon:"dee-vee-zay PAR", cat:"grammar", note:"diviser"},
  {en:"Math: equals", fr:"égale", fr_phon:"ay-GAL", cat:"grammar", note:"font / égale"},
  {en:"Answering yes/no questions", fr:"Oui / Non", fr_phon:"wee / NOHN", cat:"grammar"},
  {en:"Answering mâi questions (negative)", fr:"Si", fr_phon:"SEE", cat:"grammar", note:"'si' = yes in reply to a negative question"},
  {en:"Short question form", fr:"… non ?", fr_phon:"NOHN", cat:"grammar", note:"casual tag, e.g. 'Tu viens, non ?'"},
  {en:"Can / ability", fr:"pouvoir", fr_phon:"poo-VWAR", cat:"grammar", note:"je peux + infinitif"},
  {en:"Cannot", fr:"ne pas pouvoir", fr_phon:"nuh pa poo-VWAR", cat:"grammar", note:"je ne peux pas"},
  {en:"Can? question", fr:"Peux-tu… ?", fr_phon:"puh-TOO", cat:"grammar", note:"Est-ce que tu peux… ?"},
  {en:"Answer can? yes", fr:"Oui, je peux", fr_phon:"wee zhuh PUH", cat:"grammar"},
  {en:"Answer can? no", fr:"Non, je ne peux pas", fr_phon:"nohn zhuh nuh puh PA", cat:"grammar"},
  {en:"Literal/compound verbs", fr:"les verbes pronominaux", fr_phon:"lay vairb pro-no-mee-NOH", cat:"grammar", note:"French reflexive verbs (se laver) — closest analogue"},
  {en:"Irregular dâi verbs", fr:"(Thai-specific)", fr_phon:"", cat:"grammar", note:"no French equivalent — kept for parity, review/remove"},
  {en:"Verb-to-be 1 (bpen)", fr:"être", fr_phon:"ET-ruh", cat:"grammar", note:"C'est une table = That is a table"},
  {en:"Verb-to-be 1 negative", fr:"Ce n'est pas…", fr_phon:"suh nay PA", cat:"grammar", note:"Ce n'est pas une table"},
  {en:"Verb-to-be 2 (kheuu)", fr:"C'est…", fr_phon:"SAY", cat:"grammar", note:"C'est John = That is John"},
  {en:"Verb-to-be 2 negative", fr:"Ce n'est pas…", fr_phon:"suh nay PA", cat:"grammar", note:"Ce n'est pas Jane"},
  {en:"Verb-to-be 3 (yùu)", fr:"être (lieu)", fr_phon:"ET-ruh", cat:"grammar", note:"Il est ici = He is here"},
  {en:"Verb-to-be 3 negative", fr:"Il n'est pas…", fr_phon:"eel nay PA", cat:"grammar", note:"Il n'est pas ici"},
  {en:"This (singular)", fr:"ce / cet / cette", fr_phon:"suh / set", cat:"grammar", note:"ceci = this one"},
  {en:"These (plural)", fr:"ces", fr_phon:"SAY", cat:"grammar", note:"ceux-ci"},
  {en:"That (singular)", fr:"ce…-là", fr_phon:"suh LA", cat:"grammar", note:"cela / ça = that"},
  {en:"Those (plural)", fr:"ces…-là", fr_phon:"say LA", cat:"grammar", note:"ceux-là"},
  {en:"Where (thêe-nǎi)", fr:"où", fr_phon:"OO", cat:"grammar", note:"Où est-il ? = Where is he?"},
  {en:"Where in can? question", fr:"Où peut-on aller ?", fr_phon:"oo puh-tohn a-LAY", cat:"grammar", note:"Where can we go?"},
  {en:"Who (khrai)", fr:"qui", fr_phon:"KEE", cat:"grammar", note:"Avec qui parles-tu ? = Who are you speaking with?"},
  {en:"Whose (khâwng-khrai)", fr:"à qui", fr_phon:"a KEE", cat:"grammar", note:"À qui est ce sac ? = Whose bag is this?"},
  {en:"Possessive adjective", fr:"l'adjectif possessif", fr_phon:"la-dzhek-teef po-seh-SEEF", cat:"grammar", note:"mon, ton, son…"},
  {en:"my / mine", fr:"mon / ma / mes", fr_phon:"MOHN / MA / MAY", cat:"grammar", note:"mon (m), ma (f), mes (pl)"},
  {en:"your / yours", fr:"ton / ta / tes", fr_phon:"TOHN / TA / TAY", cat:"grammar", note:"tu form"},
  {en:"his", fr:"son / sa / ses", fr_phon:"SOHN / SA / SAY", cat:"grammar", note:"agrees with the noun, not the owner"},
  {en:"her / hers", fr:"son / sa / ses", fr_phon:"SOHN / SA / SAY", cat:"grammar", note:"identical to 'his' in French"},
  {en:"our / ours", fr:"notre / nos", fr_phon:"NOT-ruh / NOH", cat:"grammar"},
  {en:"their / theirs", fr:"leur / leurs", fr_phon:"LUR / LUR", cat:"grammar"},
  {en:"its", fr:"son / sa / ses", fr_phon:"SOHN / SA / SAY", cat:"grammar"},
  {en:"Peter's", fr:"de Peter", fr_phon:"duh PEE-tair", cat:"grammar", note:"le sac de Peter = Peter's bag (no 's possessive)"},

  // ── sentences (36) — tu register ──
  {en:"Where are you going?", fr:"Où vas-tu ?", fr_phon:"oo va-TOO", cat:"sentences"},
  {en:"I'm going to the market.", fr:"Je vais au marché.", fr_phon:"zhuh vay oh mar-SHAY", cat:"sentences"},
  {en:"How much is this?", fr:"C'est combien ?", fr_phon:"say kohn-BYAN", cat:"sentences"},
  {en:"It's too expensive.", fr:"C'est trop cher.", fr_phon:"say troh SHAIR", cat:"sentences"},
  {en:"Can you reduce the price?", fr:"Tu peux baisser le prix ?", fr_phon:"too puh beh-say luh PREE", cat:"sentences"},
  {en:"I don't understand.", fr:"Je ne comprends pas.", fr_phon:"zhuh nuh kohn-prahn PA", cat:"sentences"},
  {en:"Please speak slowly.", fr:"Parle lentement, s'il te plaît.", fr_phon:"parl lahnt-mahn seel tuh PLEH", cat:"sentences"},
  {en:"What is your name?", fr:"Comment tu t'appelles ?", fr_phon:"koh-mahn too ta-PEL", cat:"sentences"},
  {en:"My name is …", fr:"Je m'appelle …", fr_phon:"zhuh ma-PEL", cat:"sentences"},
  {en:"I don't eat spicy food.", fr:"Je ne mange pas épicé.", fr_phon:"zhuh nuh mahnzh pa zay-pee-SAY", cat:"sentences"},
  {en:"The food is delicious.", fr:"La nourriture est délicieuse.", fr_phon:"la noo-ree-tewr ay day-lee-SYUHZ", cat:"sentences"},
  {en:"I want to eat rice.", fr:"Je veux manger du riz.", fr_phon:"zhuh vuh mahn-zhay dew REE", cat:"sentences"},
  {en:"Where is the toilet?", fr:"Où sont les toilettes ?", fr_phon:"oo sohn lay twa-LET", cat:"sentences"},
  {en:"I'm lost.", fr:"Je suis perdu.", fr_phon:"zhuh swee pair-DEW", cat:"sentences", note:"f: perdue"},
  {en:"Please call a taxi.", fr:"Appelle un taxi, s'il te plaît.", fr_phon:"a-pel uhn tak-see seel tuh PLEH", cat:"sentences"},
  {en:"How far is it?", fr:"C'est loin ?", fr_phon:"say LWAN", cat:"sentences"},
  {en:"Turn left.", fr:"Tourne à gauche.", fr_phon:"toorn a GOHSH", cat:"sentences"},
  {en:"Turn right.", fr:"Tourne à droite.", fr_phon:"toorn a DRWAT", cat:"sentences"},
  {en:"Go straight.", fr:"Va tout droit.", fr_phon:"va too DRWA", cat:"sentences"},
  {en:"I feel unwell.", fr:"Je ne me sens pas bien.", fr_phon:"zhuh nuh muh sahn pa BYAN", cat:"sentences"},
  {en:"Please help me.", fr:"Aide-moi, s'il te plaît.", fr_phon:"ed-mwa seel tuh PLEH", cat:"sentences"},
  {en:"I want to go to the hospital.", fr:"Je veux aller à l'hôpital.", fr_phon:"zhuh vuh a-lay a loh-pee-TAL", cat:"sentences"},
  {en:"Can you speak English?", fr:"Tu parles anglais ?", fr_phon:"too parl ahn-GLEH", cat:"sentences"},
  {en:"A little bit.", fr:"Un petit peu.", fr_phon:"uhn puh-tee PUH", cat:"sentences"},
  {en:"I like Thailand.", fr:"J'aime la Thaïlande.", fr_phon:"zhem la ty-LAHND", cat:"sentences"},
  {en:"It's very hot today.", fr:"Il fait très chaud aujourd'hui.", fr_phon:"eel feh treh shoh oh-zhoor-DWEE", cat:"sentences"},
  {en:"Check, please.", fr:"L'addition, s'il te plaît.", fr_phon:"la-dee-syohn seel tuh PLEH", cat:"sentences", note:"asking for the bill"},
  {en:"Do you have …?", fr:"Est-ce que tu as … ?", fr_phon:"es-kuh too A", cat:"sentences"},
  {en:"I would like …", fr:"Je voudrais …", fr_phon:"zhuh voo-DREH", cat:"sentences"},
  {en:"See you again.", fr:"À bientôt.", fr_phon:"a byan-TOH", cat:"sentences"},
  {en:"Take care.", fr:"Prends soin de toi.", fr_phon:"prahn swan duh TWA", cat:"sentences"},
  {en:"Good luck!", fr:"Bonne chance !", fr_phon:"bun SHAHNS", cat:"sentences"},
  {en:"Never mind.", fr:"Ce n'est pas grave.", fr_phon:"say pa GRAHV", cat:"sentences"},
  {en:"I understand.", fr:"Je comprends.", fr_phon:"zhuh kohn-PRAHN", cat:"sentences"},
  {en:"Not yet.", fr:"Pas encore.", fr_phon:"pa zahn-KOR", cat:"sentences"},
  {en:"Already done.", fr:"C'est déjà fait.", fr_phon:"say day-zha FEH", cat:"sentences"},

  // ── alphabet (32) — Thai consonants have no French equivalent; replaced with the French alphabet + accents ──
  {en:"A", fr:"a", fr_phon:"AH", cat:"alphabet"},
  {en:"B", fr:"bé", fr_phon:"BAY", cat:"alphabet"},
  {en:"C", fr:"cé", fr_phon:"SAY", cat:"alphabet"},
  {en:"D", fr:"dé", fr_phon:"DAY", cat:"alphabet"},
  {en:"E", fr:"e", fr_phon:"UH", cat:"alphabet"},
  {en:"F", fr:"effe", fr_phon:"EFF", cat:"alphabet"},
  {en:"G", fr:"gé", fr_phon:"ZHAY", cat:"alphabet"},
  {en:"H", fr:"ache", fr_phon:"ASH", cat:"alphabet", note:"the letter H is always silent in French"},
  {en:"I", fr:"i", fr_phon:"EE", cat:"alphabet"},
  {en:"J", fr:"ji", fr_phon:"ZHEE", cat:"alphabet"},
  {en:"K", fr:"ka", fr_phon:"KA", cat:"alphabet", note:"rare in native French words"},
  {en:"L", fr:"elle", fr_phon:"EL", cat:"alphabet"},
  {en:"M", fr:"emme", fr_phon:"EM", cat:"alphabet"},
  {en:"N", fr:"enne", fr_phon:"EN", cat:"alphabet"},
  {en:"O", fr:"o", fr_phon:"OH", cat:"alphabet"},
  {en:"P", fr:"pé", fr_phon:"PAY", cat:"alphabet"},
  {en:"Q", fr:"qu", fr_phon:"KEW", cat:"alphabet"},
  {en:"R", fr:"erre", fr_phon:"AIR", cat:"alphabet", note:"guttural French r"},
  {en:"S", fr:"esse", fr_phon:"ESS", cat:"alphabet"},
  {en:"T", fr:"té", fr_phon:"TAY", cat:"alphabet"},
  {en:"U", fr:"u", fr_phon:"EW", cat:"alphabet", note:"the tricky French /y/ sound"},
  {en:"V", fr:"vé", fr_phon:"VAY", cat:"alphabet"},
  {en:"W", fr:"double vé", fr_phon:"doo-bluh VAY", cat:"alphabet", note:"rare; mostly loanwords"},
  {en:"X", fr:"iks", fr_phon:"EEKS", cat:"alphabet"},
  {en:"Y", fr:"i grec", fr_phon:"ee GREK", cat:"alphabet", note:"literally 'Greek i'"},
  {en:"Z", fr:"zède", fr_phon:"ZED", cat:"alphabet"},
  {en:"é (accent aigu)", fr:"é", fr_phon:"uh ak-sahn tay-GEW", cat:"alphabet", note:"closed 'ay' sound"},
  {en:"è (accent grave)", fr:"è", fr_phon:"uh ak-sahn GRAHV", cat:"alphabet", note:"open 'eh' sound"},
  {en:"ê (accent circonflexe)", fr:"ê", fr_phon:"uh ak-sahn seer-kohn-FLEX", cat:"alphabet", note:"often marks a dropped historical s"},
  {en:"ç (cédille)", fr:"ç", fr_phon:"say say-DEE-yuh", cat:"alphabet", note:"makes c sound like 's' before a/o/u"},
  {en:"ë / ï (tréma)", fr:"tréma", fr_phon:"tray-MA", cat:"alphabet", note:"marks a separately-pronounced vowel"},
  {en:"à (accent grave)", fr:"à", fr_phon:"a ak-sahn GRAHV", cat:"alphabet", note:"distinguishes words, e.g. a vs à"},
];
// Engine reads a global named FOUNDATION; alias it to the French deck.
const FOUNDATION = FOUNDATION_FR;
if (typeof window !== 'undefined') { window.FOUNDATION_FR = FOUNDATION_FR; window.FOUNDATION = FOUNDATION_FR; }
